'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { PROJECTS, TASKS, TODAY, comparePtDate, eventsFromProjects, type Task, type Priority, type TaskStatus, type Project } from '../_data/projects'
import { loadFreelancerProfile, type FreelancerProfile, DEFAULT_FREELANCER_PROFILE } from '../_data/freelancer-profile'
import { NotificationBell } from '../_components/NotificationBell'
import { MessagesBell } from '../_components/MessagesBell'
import { BrandLogo } from '../_components/BrandLogo'

const AVATAR_EDITOR = 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=80&h=80&fit=crop&crop=face'

/** Limpa horário "DD/MM/YYYY — HH:MM" → "DD/MM/YYYY" */
function stripTimeT(d: string): string { return (d || '').split('—')[0].trim() }

/** Converte user-project (formato de /novos-projetos) para Project tipo do _data */
function userProjectToProjectT(p: any): Project {
  const pacote = p.pacote ?? 'Pacote Premium 👑'
  return {
    id: p.id,
    noivos: p.noivos ?? '—',
    foto: p.foto || 'https://images.unsplash.com/photo-1519741497674-611481863552?w=900&h=600&fit=crop',
    email: '', telefone: '',
    recebido: stripTimeT(p.recebido || ''),
    dataCasamento: p.dataCasamento || '',
    entregaPrevista: p.entregaPrevista || '',
    pacote, preco: pacote === 'Pacote Essencial' ? 1800 : 3500,
    duracao: p.duracao || '',
    stage: p.stage ?? 'Novo Projeto',
    approval: p.approval ?? 'Aguardando Revisão',
    progress: 0,
    editor: p.editor || 'Editor Pro',
    finalEntregue: p.stage === 'Entregue',
    finalLink: p.finalLink || '',
  }
}

/** Gera tarefas automáticas para um projeto criado pelo utilizador */
function generateTasksForUserProject(p: any): Task[] {
  const auto: { title: string; priority: Priority; daysAfterCreate: number }[] = [
    { title: 'Importar material',     priority: 'Alta',  daysAfterCreate: 0 },
    { title: 'Organizar ficheiros',   priority: 'Média', daysAfterCreate: 1 },
    { title: 'Iniciar edição',        priority: 'Alta',  daysAfterCreate: 3 },
    { title: 'Color grading',         priority: 'Média', daysAfterCreate: 7 },
    { title: 'Enviar primeira versão', priority: 'Alta', daysAfterCreate: 14 },
  ]
  const recebido = stripTimeT(p.recebido || TODAY)
  const [d, m, y] = recebido.split('/').map(Number)
  return auto.map((t, i) => {
    const dt = new Date(y, m-1, d); dt.setDate(dt.getDate() + t.daysAfterCreate)
    const deadline = `${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}`
    return {
      id: `${p.id}-task-${i}`,
      title: t.title,
      projectId: p.id,
      assignee: 'Editor Pro',
      assigneeAvatar: AVATAR_EDITOR,
      deadline,
      priority: t.priority,
      status: 'Pendente' as TaskStatus,
      progress: 0,
      autoGenerated: true,
    }
  })
}

// ────────────────────────────────────────────────────────────────────────
//  TAREFAS — Wedding Moments Films
// ────────────────────────────────────────────────────────────────────────

const NAV_ITEMS = [
  { key: 'dashboard',   label: 'Dashboard',           icon: '⌂', href: '/painel-editor' },
  { key: 'novos',       label: 'Novos Projetos',      icon: '+', href: '/painel-editor/novos-projetos' },
  { key: 'pagamentos',  label: 'Pagamentos',          icon: '€', href: '/painel-editor/pagamentos' },
  { key: 'tarefas',     label: 'Tarefas',             icon: '◷', href: '/painel-editor/tarefas', active: true },
  { key: 'calendario',  label: 'Calendário',          icon: '◉', href: '/painel-editor/calendario' },
  { key: 'workflow',    label: 'Workflow',            icon: '☰', href: '/painel-editor/workflow' },
  { key: 'biblioteca',  label: 'Biblioteca',          icon: '♪', href: '/painel-editor/musicas' },
  { key: 'dados',       label: 'Dados Pessoais',      icon: '☻', href: '/painel-editor/dados-pessoais' },
]

const FILTERS = ['Todas','Pendentes','Em andamento','Concluídas','Atrasadas','Alta prioridade','Minha equipa'] as const
type FilterTab = typeof FILTERS[number]

function priorityBadge(p: Priority) {
  if (p === 'Alta')  return 'bg-red-500/15 text-red-300 border-red-500/30'
  if (p === 'Média') return 'bg-yellow-500/15 text-yellow-300 border-yellow-500/30'
  return 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30'
}

// Lookup global de projetos (mocks + user-projects do localStorage)
// É preenchido em runtime via getAllProjectsLookup()
let _projectsLookup: Project[] = [...PROJECTS]
function getProjectsLookup() { return _projectsLookup }
function setProjectsLookup(arr: Project[]) { _projectsLookup = arr }
function projectFor(projectId: string) {
  return getProjectsLookup().find(p => p.id === projectId)
}

function isOverdue(t: Task) {
  return t.status !== 'Concluída' && t.status !== 'Cancelada' && comparePtDate(t.deadline, TODAY) < 0
}

function deadlineLabel(date: string): string {
  if (date === TODAY) return 'Hoje'
  const [d,m,y] = date.split('/').map(Number)
  const [td,tm,ty] = TODAY.split('/').map(Number)
  const target = new Date(y, m-1, d).getTime()
  const today = new Date(ty, tm-1, td).getTime()
  const diff = Math.round((target - today) / 86400000)
  if (diff === 1) return 'Amanhã'
  if (diff === -1) return 'Ontem'
  if (diff > 1 && diff < 8) return `${diff} dias`
  if (diff < 0 && diff > -8) return `${Math.abs(diff)} dias atrás`
  const meses = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
  return `${String(d).padStart(2,'0')} ${meses[m-1]}`
}

const USER_TASKS_STORAGE_KEY = 'painel-editor-user-tasks'
const DELETED_TASKS_STORAGE_KEY = 'painel-editor-deleted-tasks'

export default function TarefasPage() {
  const [tasks, setTasks] = useState<Task[]>(TASKS)
  const [userTasks, setUserTasks] = useState<Task[]>([])
  const [deletedIds, setDeletedIds] = useState<Set<string>>(new Set())
  const [filter, setFilter] = useState<FilterTab>('Todas')
  const [search, setSearch] = useState('')
  const [showCompleted, setShowCompleted] = useState(false)
  const [showNewTaskModal, setShowNewTaskModal] = useState(false)
  const [completingTask, setCompletingTask] = useState<Task | null>(null)   // task que está prestes a ser marcada como Concluída

  // ── Sincroniza com user-projects (localStorage) ─────────────────────
  useEffect(() => {
    function load() {
      try {
        const raw = localStorage.getItem('painel-editor-user-projects')
        const userProjects: any[] = raw ? JSON.parse(raw) : []

        // Detecta mocks eliminados via patches
        const patchesRaw = localStorage.getItem('painel-editor-project-patches')
        const patches: Record<string, any> = patchesRaw ? JSON.parse(patchesRaw) : {}
        const deletedIds = new Set<string>()
        Object.entries(patches).forEach(([id, patch]) => {
          if (patch?.archived || patch?.cancelled) deletedIds.add(id)
        })

        // 1) Adiciona user-projects ao lookup global (para projectFor()) — filtra mocks eliminados
        const userMappedProjects: Project[] = userProjects.map(userProjectToProjectT)
        const aliveMocks = PROJECTS.filter(p => !deletedIds.has(p.id))
        setProjectsLookup([...userMappedProjects, ...aliveMocks])

        // 2) Gera tarefas automáticas para cada user-project
        const autoUserTasks: Task[] = userProjects.flatMap(generateTasksForUserProject)

        // 3) Carrega tarefas criadas manualmente pelo user
        const userTasksRaw = localStorage.getItem(USER_TASKS_STORAGE_KEY)
        const userCreatedTasks: Task[] = userTasksRaw ? JSON.parse(userTasksRaw) : []
        setUserTasks(userCreatedTasks)

        // 3b) Carrega tarefas eliminadas pelo user (ids ocultos persistidos)
        const deletedRaw = localStorage.getItem(DELETED_TASKS_STORAGE_KEY)
        const deletedTaskIds: string[] = deletedRaw ? JSON.parse(deletedRaw) : []
        const deletedTaskSet = new Set(deletedTaskIds)
        setDeletedIds(deletedTaskSet)

        // 4) Merge: user-criadas + auto-geradas + mock TASKS
        //    (filtra tarefas de projetos eliminados E tarefas explicitamente eliminadas)
        const allTasks = [...userCreatedTasks, ...autoUserTasks, ...TASKS]
          .filter(t => !deletedIds.has(t.projectId))
          .filter(t => !deletedTaskSet.has(t.id))
        setTasks(allTasks)
      } catch {
        setProjectsLookup([...PROJECTS])
        setTasks(TASKS)
      }
    }
    load()
    const onFocus = () => load()
    window.addEventListener('focus', onFocus)
    return () => window.removeEventListener('focus', onFocus)
  }, [])

  // Persistir tarefas criadas manualmente sempre que mudam
  useEffect(() => {
    try {
      localStorage.setItem(USER_TASKS_STORAGE_KEY, JSON.stringify(userTasks))
    } catch {}
  }, [userTasks])

  function addTask(newTask: Task) {
    setUserTasks(prev => [newTask, ...prev])
    setTasks(prev => [newTask, ...prev])
    // Marca tarefa como "não vista" para brilhar no widget do dashboard até ser aberta
    try {
      const raw = localStorage.getItem('painel-editor-unseen-tasks')
      const arr: string[] = raw ? JSON.parse(raw) : []
      if (!arr.includes(newTask.id)) arr.push(newTask.id)
      localStorage.setItem('painel-editor-unseen-tasks', JSON.stringify(arr))
    } catch {}
  }

  function deleteTask(id: string) {
    // Remove da lista visível e de userTasks (caso seja user-criada)
    setTasks(prev => prev.filter(t => t.id !== id))
    setUserTasks(prev => prev.filter(t => t.id !== id))
    // Persiste o id em deletedIds para que mocks/auto-tarefas não reapareçam
    setDeletedIds(prev => {
      if (prev.has(id)) return prev
      const next = new Set(prev); next.add(id)
      try { localStorage.setItem(DELETED_TASKS_STORAGE_KEY, JSON.stringify([...next])) } catch {}
      return next
    })
  }

  // Filtros
  const filtered = useMemo(() => {
    let arr = tasks
    if (filter === 'Pendentes')       arr = arr.filter(t => t.status === 'Pendente')
    else if (filter === 'Em andamento') arr = arr.filter(t => t.status === 'Em andamento')
    else if (filter === 'Concluídas')   arr = arr.filter(t => t.status === 'Concluída')
    else if (filter === 'Atrasadas')    arr = arr.filter(t => isOverdue(t))
    else if (filter === 'Alta prioridade') arr = arr.filter(t => t.priority === 'Alta')
    else if (filter === 'Minha equipa') arr = arr.filter(t => t.assignee === 'Editor Pro')
    if (search.trim()) arr = arr.filter(t => t.title.toLowerCase().includes(search.toLowerCase()))
    return arr
  }, [tasks, filter, search])

  // Agrupar
  const hoje      = filtered.filter(t => t.deadline === TODAY && (showCompleted || t.status !== 'Concluída'))
  const proximas  = filtered.filter(t => t.deadline !== TODAY && comparePtDate(t.deadline, TODAY) > 0 && t.status !== 'Concluída')
                            .sort((a, b) => comparePtDate(a.deadline, b.deadline))
  const atrasadas = filtered.filter(t => isOverdue(t) && t.deadline !== TODAY)
  const concluidas = filtered.filter(t => t.status === 'Concluída' && t.deadline !== TODAY)

  // Counts (todas, sem filtro)
  const counts = useMemo(() => ({
    total:        tasks.length,
    pendentes:    tasks.filter(t => t.status === 'Pendente').length,
    emAndamento:  tasks.filter(t => t.status === 'Em andamento').length,
    concluidas:   tasks.filter(t => t.status === 'Concluída').length,
    atrasadas:    tasks.filter(t => isOverdue(t)).length,
  }), [tasks])

  // Donut chart
  const donut = useMemo(() => {
    const total = counts.pendentes + counts.emAndamento + counts.concluidas + counts.atrasadas
    if (total === 0) return { segments: [], total: 0 }
    const segs: { color: string; from: number; to: number }[] = []
    let acc = 0
    const items = [
      { value: counts.pendentes,   color: '#94a3b8' }, // pendentes — cinza
      { value: counts.emAndamento, color: '#facc15' }, // gold/amarelo
      { value: counts.concluidas,  color: '#34d399' }, // verde
      { value: counts.atrasadas,   color: '#ef4444' }, // vermelho
    ]
    items.forEach(it => {
      if (it.value === 0) return
      const from = acc
      const to = acc + (it.value / total) * 360
      segs.push({ color: it.color, from, to })
      acc = to
    })
    return { segments: segs, total }
  }, [counts])

  // Toggle status — só permite Pendente → Concluída (com modal de resultado).
  // Tarefa Concluída fica TRANCADA: não pode ser revertida (regra de negócio).
  function toggleTask(id: string) {
    const task = tasks.find(t => t.id === id)
    if (!task) return
    if (task.status === 'Concluída') {
      // Bloqueado: não há reversão de Concluída.
      return
    }
    // Concluir: abrir modal para escrever resultado
    setCompletingTask(task)
  }

  function completeTaskWithResultado(id: string, resultado: string) {
    const now = new Date()
    const tm = `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`
    const update = (t: Task): Task =>
      t.id !== id ? t : { ...t, status: 'Concluída', progress: 100, completedAt: `${TODAY} — ${tm}`, resultado: resultado.trim() }
    setTasks(prev => prev.map(update))
    setUserTasks(prev => prev.map(update))
    setCompletingTask(null)
  }

  // Calendário — hoje derivado da constante TODAY
  const [_td, _tm, _ty] = TODAY.split('/').map(Number)
  const calToday = new Date(_ty, _tm - 1, _td)
  const [calView, setCalView] = useState({ y: _ty, m: _tm - 1 })
  const firstDay = new Date(calView.y, calView.m, 1).getDay()
  const lastDate = new Date(calView.y, calView.m + 1, 0).getDate()
  const prevLastDate = new Date(calView.y, calView.m, 0).getDate()

  // Sincronizado com /calendario: marca dias com TAREFAS + EVENTOS DE PROJETOS
  // (Casamento, Material Recebido, Início Edição, Revisão V1/V2, Entrega Trailer/Final, Pagamento)
  const baseEvents = useMemo(() => eventsFromProjects(), [])
  const userProjectEvents = useMemo(() => {
    if (typeof window === 'undefined') return [] as { date: string }[]
    try {
      const raw = localStorage.getItem('painel-editor-user-projects')
      const userProjects: any[] = raw ? JSON.parse(raw) : []
      const evts: { date: string }[] = []
      const addDaysPt = (date: string, days: number): string => {
        const cleaned = (date || '').split('—')[0].trim()
        const [d, m, y] = cleaned.split('/').map(Number)
        if (!d || !m || !y) return ''
        const dt = new Date(y, m-1, d); dt.setDate(dt.getDate() + days)
        return `${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}`
      }
      userProjects.forEach(p => {
        const recebido = (p.recebido || '').split('—')[0].trim()
        if (recebido) {
          evts.push({ date: recebido })
          evts.push({ date: addDaysPt(recebido, 5) })   // Início Edição
        }
        if (p.dataCasamento) evts.push({ date: p.dataCasamento })
        if (p.entregaPrevista) {
          evts.push({ date: addDaysPt(p.entregaPrevista, -10) })
          evts.push({ date: addDaysPt(p.entregaPrevista, -7) })
          evts.push({ date: addDaysPt(p.entregaPrevista, -5) })
          evts.push({ date: addDaysPt(p.entregaPrevista, -3) })
          evts.push({ date: p.entregaPrevista })
        }
      })
      return evts
    } catch { return [] as { date: string }[] }
  }, [tasks])  // re-roda quando tasks muda (proxy para localStorage updates)

  // Conta eventos por dia (tarefas + projetos)
  const markedDays = useMemo(() => {
    const counts = new Map<number, number>()
    const inc = (d: number) => counts.set(d, (counts.get(d) ?? 0) + 1)
    // Tarefas no mês atual
    tasks.forEach(t => {
      const [d, m, y] = (t.deadline || '').split('/').map(Number)
      if (y === calView.y && m - 1 === calView.m && d) inc(d)
    })
    // Eventos de projetos (mock + user) no mês atual
    ;[...baseEvents, ...userProjectEvents].forEach(e => {
      const [d, m, y] = (e.date || '').split('/').map(Number)
      if (y === calView.y && m - 1 === calView.m && d) inc(d)
    })
    return counts
  }, [tasks, baseEvents, userProjectEvents, calView])

  type Cell = { day: number; current: boolean; isToday: boolean; hasTask: boolean; iso?: string }
  const cells: Cell[] = []
  for (let i = firstDay - 1; i >= 0; i--) cells.push({ day: prevLastDate - i, current: false, isToday: false, hasTask: false })
  for (let d = 1; d <= lastDate; d++) {
    const isToday = calView.y === calToday.getFullYear() && calView.m === calToday.getMonth() && d === calToday.getDate()
    const iso = `${calView.y}-${String(calView.m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`
    cells.push({ day: d, current: true, isToday, hasTask: (markedDays.get(d) ?? 0) > 0, iso })
  }
  while (cells.length % 7 !== 0) cells.push({ day: cells.length - lastDate - firstDay + 1, current: false, isToday: false, hasTask: false })

  // Próximos Prazos (1 destacado como na screenshot)
  const proxPrazo = proximas[0] ?? atrasadas[0] ?? hoje[0]

  return (
    <div className="min-h-screen text-white relative" style={{ background: '#0A0A0A' }}>
      <div className="pointer-events-none fixed inset-0 z-0" style={{ background: 'radial-gradient(ellipse 80% 60% at 80% 15%, rgba(201,164,92,0.07), transparent 65%)' }} />
      <div className="pointer-events-none fixed inset-0 z-0" style={{ background: 'radial-gradient(ellipse 60% 50% at 15% 85%, rgba(201,164,92,0.05), transparent 70%)' }} />

      <Sidebar />

      <main className="relative z-10 md:pl-[250px]">
        <div className="px-6 sm:px-8 py-6 max-w-[1600px] mx-auto">

          {/* HERO */}
          <Hero onNovaTarefa={() => setShowNewTaskModal(true)} />

          {/* GRID */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 mt-5">

            {/* MAIN COLUMN — Lista de tarefas */}
            <div className="lg:col-span-2 flex flex-col gap-4">

              {/* Filter Bar */}
              <div className="rounded-2xl border border-white/[0.06] p-4 backdrop-blur-md"
                style={{ background: 'linear-gradient(135deg, rgba(20,15,8,0.4), rgba(11,11,11,0.5))' }}>
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div className="flex flex-wrap items-center gap-1">
                    {FILTERS.slice(0, 5).map(f => (
                      <button key={f} onClick={() => setFilter(f)}
                        className={`relative px-3 py-2 text-[13px] tracking-wide transition-all ${
                          filter === f
                            ? 'text-gold'
                            : 'text-white/45 hover:text-white/80'
                        }`}>
                        {f}
                        {filter === f && <span className="absolute bottom-0 left-3 right-3 h-px bg-gold" />}
                      </button>
                    ))}
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="relative">
                      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30 text-[14px]">⌕</span>
                      <input value={search} onChange={e => setSearch(e.target.value)}
                        placeholder="Pesquisar tarefa…"
                        className="bg-black/30 border border-white/[0.08] rounded-lg pl-9 pr-3 py-2 text-[12px] text-white placeholder:text-white/30 focus:outline-none focus:border-gold/40 w-60" />
                    </div>
                    <button className="inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-white/[0.08] text-white/55 hover:text-gold hover:border-gold/30 transition-all text-[12px]">
                      ⚙ Filtros
                    </button>
                  </div>
                </div>
              </div>

              {/* Group: Tarefas de Hoje */}
              {hoje.length > 0 && (
                <Section title="Tarefas de Hoje" count={hoje.length}>
                  {hoje.map(t => <TaskRow key={t.id} t={t} onToggle={() => toggleTask(t.id)} onDelete={() => deleteTask(t.id)} />)}
                </Section>
              )}

              {/* Group: Atrasadas */}
              {atrasadas.length > 0 && (
                <Section title="Atrasadas" count={atrasadas.length} accent="red">
                  {atrasadas.map(t => <TaskRow key={t.id} t={t} onToggle={() => toggleTask(t.id)} onDelete={() => deleteTask(t.id)} />)}
                </Section>
              )}

              {/* Group: Próximas Tarefas */}
              {proximas.length > 0 && (
                <Section title="Próximas Tarefas" count={proximas.length}>
                  {proximas.map(t => <TaskRow key={t.id} t={t} onToggle={() => toggleTask(t.id)} onDelete={() => deleteTask(t.id)} />)}
                </Section>
              )}

              {/* Mostrar concluídas */}
              {!showCompleted && concluidas.length > 0 && (
                <button onClick={() => setShowCompleted(true)}
                  className="w-full py-3 rounded-2xl border border-white/[0.06] bg-white/[0.02] text-[12px] tracking-widest uppercase text-white/45 hover:text-gold hover:border-gold/30 transition-all">
                  Mostrar concluídas ({concluidas.length}) ⌄
                </button>
              )}
              {showCompleted && concluidas.length > 0 && (
                <Section title="Concluídas" count={concluidas.length} accent="emerald">
                  {concluidas.map(t => <TaskRow key={t.id} t={t} onToggle={() => toggleTask(t.id)} onDelete={() => deleteTask(t.id)} />)}
                </Section>
              )}

              {filtered.length === 0 && (
                <div className="rounded-2xl border border-dashed border-white/[0.08] text-center py-16">
                  <p className="text-gold/40 text-4xl font-serif leading-none mb-3">∅</p>
                  <p className="text-[14px] text-white/35">Sem tarefas com este filtro.</p>
                </div>
              )}
            </div>

            {/* RIGHT — Sidebar painéis */}
            <aside className="lg:col-span-1 flex flex-col gap-4">

              {/* Visão Geral (donut) */}
              <Panel title="Visão Geral">
                <div className="flex items-center gap-5">
                  <Donut segments={donut.segments} total={donut.total} />
                  <div className="flex-1 space-y-2.5">
                    <Legend color="#94a3b8" label="Pendentes"   value={counts.pendentes} />
                    <Legend color="#facc15" label="Em andamento" value={counts.emAndamento} />
                    <Legend color="#34d399" label="Concluídas"   value={counts.concluidas} />
                    <Legend color="#ef4444" label="Atrasada"     value={counts.atrasadas} />
                  </div>
                </div>
              </Panel>

              {/* Sincronização */}
              <div className="rounded-2xl border border-emerald-500/15 p-4 backdrop-blur-md"
                style={{ background: 'linear-gradient(135deg, rgba(16,40,28,0.4), rgba(11,11,11,0.5))' }}>
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-300 text-lg shrink-0">
                    ↻
                  </div>
                  <div className="flex-1">
                    <p className="text-[13px] font-semibold text-white mb-0.5">Sincronização</p>
                    <p className="text-[11px] text-white/50 leading-relaxed">Todas as tarefas estão sincronizadas com os projetos e prazos.</p>
                    <p className="text-[11px] text-emerald-300 mt-2 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" style={{ boxShadow: '0 0 6px rgba(52,211,153,0.7)' }} />
                      Sincronizado agora
                    </p>
                  </div>
                </div>
              </div>

              {/* Calendário */}
              <Panel title="Calendário" right={
                <div className="flex items-center gap-2">
                  <button onClick={() => { const d = new Date(calView.y, calView.m - 1, 1); setCalView({ y: d.getFullYear(), m: d.getMonth() }) }}
                    className="w-6 h-6 rounded-md border border-white/10 text-white/50 hover:text-gold hover:border-gold/30 transition-all text-[12px]">‹</button>
                  <button onClick={() => { setCalView({ y: _ty, m: _tm - 1 }) }}
                    className="text-[11px] tracking-widest uppercase text-white/45 hover:text-gold transition-colors px-2 py-1 rounded-md border border-white/10">Hoje</button>
                  <button onClick={() => { const d = new Date(calView.y, calView.m + 1, 1); setCalView({ y: d.getFullYear(), m: d.getMonth() }) }}
                    className="w-6 h-6 rounded-md border border-white/10 text-white/50 hover:text-gold hover:border-gold/30 transition-all text-[12px]">›</button>
                </div>
              }>
                <p className="text-center text-[14px] tracking-wider text-white/85 mb-3 font-light">
                  {['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][calView.m]} {calView.y}
                </p>
                <div className="grid grid-cols-7 gap-1 mb-1">
                  {['D','S','T','Q','Q','S','S'].map((d, i) => (
                    <div key={i} className="text-center text-[10px] tracking-widest uppercase text-white/30 py-1.5">{d}</div>
                  ))}
                </div>
                <div className="grid grid-cols-7 gap-1">
                  {cells.map((c, i) => {
                    const href = c.iso ? `/painel-editor/calendario?date=${c.iso}` : '/painel-editor/calendario'
                    const cls = `w-full h-full flex items-center justify-center text-[12px] rounded-md transition-all ${
                      c.isToday
                        ? 'bg-gold text-black font-bold'
                        : c.hasTask && c.current
                          ? 'text-gold border border-gold/30 hover:bg-gold/10'
                          : c.current
                            ? 'text-white/65 hover:bg-white/[0.04]'
                            : 'text-white/15'
                    }`
                    return (
                      <div key={i} className="aspect-square relative">
                        {c.current ? (
                          <Link href={href} className={cls}
                            style={c.isToday ? { boxShadow: '0 0 12px rgba(201,164,92,0.5)' } : {}}
                            title="Abrir no Calendário">
                            {c.day}
                          </Link>
                        ) : (
                          <span className={cls}>{c.day}</span>
                        )}
                        {c.hasTask && c.current && !c.isToday && (
                          <span className="absolute bottom-0.5 left-1/2 -translate-x-1/2 w-1 h-1 rounded-full bg-gold pointer-events-none" />
                        )}
                      </div>
                    )
                  })}
                </div>
              </Panel>

              {/* Próximos Prazos */}
              <Panel title="Próximos Prazos" right={<button className="text-[11px] tracking-wider uppercase text-white/40 hover:text-gold transition-colors">Ver todos</button>}>
                <div className="space-y-2">
                  {(proxPrazo ? [proxPrazo, ...proximas.slice(1, 3)] : proximas.slice(0, 3)).filter(Boolean).map((t, i) => {
                    const proj = projectFor(t.projectId)
                    const [d, m] = t.deadline.split('/').map(Number)
                    const meses = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
                    return (
                      <div key={i} className="flex items-center gap-3 p-3 rounded-xl border border-white/[0.06] hover:border-gold/30 hover:bg-white/[0.02] transition-all">
                        {proj && (
                          <div className="w-12 h-12 rounded-lg overflow-hidden border border-white/10 shrink-0">
                            <img src={proj.foto} alt="" className="w-full h-full object-cover" />
                          </div>
                        )}
                        <div className="flex-1 min-w-0">
                          <p className="text-[12px] font-medium text-white truncate">{t.title}</p>
                          <p className="text-[11px] text-white/40 truncate">{proj?.noivos ?? '—'}</p>
                          <p className="text-[10px] text-white/35 mt-0.5">{String(d).padStart(2,'0')} {meses[m-1]}</p>
                        </div>
                        <span className={`text-[10px] px-2 py-0.5 rounded-md border tracking-widest uppercase font-bold ${
                          isOverdue(t) ? 'bg-red-500/15 text-red-300 border-red-500/30' : 'bg-gold/15 text-gold border-gold/30'
                        }`}>
                          {deadlineLabel(t.deadline)}
                        </span>
                      </div>
                    )
                  })}
                </div>
              </Panel>
            </aside>
          </div>

          <p className="text-center text-[10px] tracking-[0.4em] uppercase text-white/15 mt-12 mb-4">RL Photo.Video · Tarefas sincronizadas</p>
        </div>
      </main>

      {/* Modal Nova Tarefa */}
      {showNewTaskModal && (
        <NovaTarefaModal
          projects={getProjectsLookup()}
          onClose={() => setShowNewTaskModal(false)}
          onCreate={(t) => { addTask(t); setShowNewTaskModal(false) }}
        />
      )}

      {/* Modal Concluir Tarefa — obriga a escrever resultado */}
      {completingTask && (
        <ConcluirTarefaModal
          task={completingTask}
          onClose={() => setCompletingTask(null)}
          onConfirm={(resultado) => completeTaskWithResultado(completingTask.id, resultado)}
        />
      )}
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────────
//  COMPONENTS
// ────────────────────────────────────────────────────────────────────────

function Sidebar() {
  return (
    <aside
      className="hidden md:flex fixed top-0 left-0 bottom-0 w-[250px] z-30 flex-col"
      style={{
        background: 'linear-gradient(180deg, rgba(15,12,8,0.96) 0%, rgba(11,9,5,0.98) 100%)',
        backdropFilter: 'blur(20px)',
        borderRight: '1px solid rgba(201,164,92,0.12)',
      }}>
      {/* Logo */}
      <BrandLogo />
      {/* Nav */}
      <nav className="flex-1 overflow-y-auto px-3 py-5 space-y-0.5">
        {NAV_ITEMS.map(it => {
          const isActive = !!it.active
          const cls = `w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-left transition-all group ${
            isActive ? 'bg-gold/10 border border-gold/30 text-gold' : 'border border-transparent text-white/45 hover:text-white/90 hover:bg-white/[0.03]'
          }`
          const inner = (
            <>
              <span className={`w-5 text-center text-base ${isActive ? 'text-gold' : 'text-white/35 group-hover:text-white/70'}`}>{it.icon}</span>
              <span className="text-[13px] font-medium tracking-wide">{it.label}</span>
            </>
          )
          return it.href
            ? <Link key={it.key} href={it.href} className={cls} style={isActive ? { boxShadow: '0 0 18px -4px rgba(201,164,92,0.35)' } : {}}>{inner}</Link>
            : <button key={it.key} className={cls}>{inner}</button>
        })}
      </nav>

      {/* Quote */}
      <div className="px-4 pb-3">
        <div className="rounded-xl border border-gold/15 p-3"
          style={{ background: 'linear-gradient(135deg, rgba(201,164,92,0.06), transparent)' }}>
          <div className="flex items-start gap-2">
            <span className="text-gold text-base">📝</span>
            <p className="text-[10px] text-white/50 italic leading-relaxed">Todas as tarefas sincronizadas com os projetos.</p>
          </div>
          <button className="mt-2 text-[10px] tracking-widest uppercase text-gold/80 hover:text-gold transition-colors flex items-center gap-1">
            Saber mais <span>→</span>
          </button>
        </div>
      </div>

      {/* Profile */}
      <div className="px-4 py-3 border-t border-white/[0.04]">
        <div className="flex items-center gap-3 p-2 rounded-xl bg-white/[0.02] border border-white/[0.06]">
          <div className="relative w-10 h-10 rounded-full overflow-hidden border border-gold/40 shrink-0">
            <img src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=80&h=80&fit=crop&crop=face" alt="" className="w-full h-full object-cover" />
            <span className="absolute bottom-0 right-0 w-2.5 h-2.5 rounded-full bg-emerald-400 border border-black" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-[12px] font-semibold text-white truncate">Editor Pro</p>
            <p className="text-[10px] text-white/35 truncate">editorpro@mail.com</p>
            <p className="text-[9px] text-emerald-400 mt-0.5">● Online</p>
          </div>
        </div>
      </div>
    </aside>
  )
}

function Hero({ onNovaTarefa }: { onNovaTarefa: () => void }) {
  return (
    <div className="relative overflow-hidden rounded-3xl border border-white/[0.08]"
      style={{ boxShadow: '0 30px 60px -20px rgba(0,0,0,0.6)' }}>
      <div className="absolute inset-0 z-0">
        <img src="https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1600&h=300&fit=crop"
          alt="" className="w-full h-full object-cover" style={{ filter: 'blur(1.5px)' }} />
      </div>
      <div className="absolute inset-0 z-[1]"
        style={{ background: 'linear-gradient(90deg, rgba(10,10,10,0.96) 0%, rgba(10,10,10,0.85) 35%, rgba(10,10,10,0.45) 70%, rgba(10,10,10,0.05) 100%)' }} />
      <div className="relative z-10 flex items-center justify-between gap-6 px-8 sm:px-12 py-8">
        <div className="flex items-center gap-5 max-w-xl">
          <div className="w-16 h-16 rounded-2xl border border-gold/40 flex items-center justify-center text-3xl text-gold shrink-0"
            style={{ background: 'radial-gradient(circle at 30% 30%, rgba(201,164,92,0.18), rgba(201,164,92,0.04))', boxShadow: '0 0 22px -4px rgba(201,164,92,0.3)' }}>📋</div>
          <div>
            <h1 className="text-4xl sm:text-5xl font-light text-white tracking-tight" style={{ fontFamily: 'Georgia, serif' }}>Tarefas</h1>
            <p className="text-[13px] text-white/55 mt-1 leading-relaxed">Gerencia todas as tuas tarefas. Sincronizadas com os teus projetos e prazos.</p>
            <div className="mt-2 h-px w-14 bg-gradient-to-r from-gold/70 to-transparent" />
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <NotificationBell />
          <MessagesBell />
          <button
            type="button"
            onClick={onNovaTarefa}
            className="inline-flex items-center gap-2 px-5 h-11 rounded-xl bg-gold text-black text-[13px] font-semibold tracking-wider hover:bg-gold/90 transition-all"
            style={{ boxShadow: '0 0 24px -4px rgba(201,164,92,0.5)' }}>
            <span className="text-lg leading-none">+</span> Nova Tarefa
          </button>
        </div>
      </div>
    </div>
  )
}

function Section({ title, count, accent, children }: { title: string; count: number; accent?: 'red'|'emerald'; children: React.ReactNode }) {
  const accentCls =
    accent === 'red'     ? 'bg-red-500/15 text-red-300 border-red-500/30' :
    accent === 'emerald' ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30' :
                           'bg-gold/15 text-gold border-gold/30'
  return (
    <div className="rounded-2xl border border-white/[0.06] backdrop-blur-md p-5"
      style={{ background: 'linear-gradient(135deg, rgba(20,15,8,0.35), rgba(11,11,11,0.65))', boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)' }}>
      <div className="flex items-center gap-2 mb-4">
        <h3 className="text-[15px] font-semibold text-white" style={{ fontFamily: 'Georgia, serif' }}>{title}</h3>
        <span className={`inline-flex items-center justify-center min-w-[24px] h-5 px-1.5 rounded-full text-[11px] font-bold border ${accentCls}`}>{count}</span>
      </div>
      <div className="space-y-1.5">
        {children}
      </div>
    </div>
  )
}

function TaskRow({ t, onToggle, onDelete }: { t: Task; onToggle: () => void; onDelete: () => void }) {
  const proj = projectFor(t.projectId)
  const done = t.status === 'Concluída'
  const overdue = isOverdue(t)
  const [menuOpen, setMenuOpen] = useState(false)

  // Fecha menu ao clicar fora
  useEffect(() => {
    if (!menuOpen) return
    const close = () => setMenuOpen(false)
    // Pequeno timeout para não fechar com o próprio click de abertura
    const id = setTimeout(() => window.addEventListener('click', close), 0)
    return () => { clearTimeout(id); window.removeEventListener('click', close) }
  }, [menuOpen])

  return (
    <div className="group flex items-center gap-4 p-3 rounded-xl border border-transparent hover:border-gold/20 hover:bg-white/[0.02] transition-all">
      {/* Checkbox — quando Concluída fica trancada (não permite reverter) */}
      <button
        onClick={done ? undefined : onToggle}
        disabled={done}
        title={done ? 'Tarefa concluída — não é possível reverter' : 'Marcar como concluída'}
        className={`w-6 h-6 rounded-full border-2 flex items-center justify-center shrink-0 transition-all ${
          done
            ? 'bg-emerald-500 border-emerald-500 cursor-not-allowed'
            : 'border-white/25 hover:border-gold/60 cursor-pointer'
        }`}>
        {done && <span className="text-[12px] text-black font-bold">✓</span>}
      </button>

      {/* Info */}
      <div className="flex-1 min-w-0">
        <p className={`text-[14px] font-medium leading-tight ${done ? 'line-through text-white/35' : 'text-white'}`}>{t.title}</p>
        <p className="text-[11px] mt-0.5 truncate">
          {proj
            ? <span className="text-white/40">{proj.noivos}</span>
            : <span className="text-white/25 italic">Sem projeto associado</span>}
        </p>
        {t.completedAt && <p className="text-[10px] text-emerald-400/70 mt-0.5">✓ Concluída · {t.completedAt}</p>}
        {done && t.resultado && (
          <div className="mt-1.5 pl-2 border-l-2 border-emerald-500/40">
            <p className="text-[10px] tracking-widest uppercase text-emerald-400/60 font-bold">Resultado</p>
            <p className="text-[11px] text-white/65 leading-snug mt-0.5 line-clamp-2">{t.resultado}</p>
          </div>
        )}
      </div>

      {/* Priority */}
      <span className={`text-[10px] px-2.5 py-1 rounded-full border tracking-widest uppercase font-bold shrink-0 ${priorityBadge(t.priority)}`}>
        {t.priority}
      </span>

      {/* Deadline */}
      <div className={`hidden sm:inline-flex items-center gap-1.5 text-[11px] shrink-0 ${overdue ? 'text-red-300' : 'text-white/60'}`}>
        <span>📅</span>
        <span>{deadlineLabel(t.deadline)}</span>
      </div>

      {/* Avatar */}
      <div className="w-8 h-8 rounded-full overflow-hidden border border-white/15 shrink-0" title={t.assignee}>
        {t.assigneeAvatar ? (
          <img src={t.assigneeAvatar} alt={t.assignee} className="w-full h-full object-cover" />
        ) : (
          <div className="w-full h-full bg-gold/15 flex items-center justify-center text-gold text-xs font-bold">{t.assignee.charAt(0)}</div>
        )}
      </div>

      {/* Menu */}
      <div className="relative shrink-0" onClick={e => e.stopPropagation()}>
        <button onClick={() => setMenuOpen(v => !v)}
          className="w-8 h-8 rounded-lg text-white/35 hover:text-gold hover:bg-white/[0.04] transition-all flex items-center justify-center">⋮</button>
        {menuOpen && (
          <div className="absolute right-0 top-9 w-52 rounded-xl border border-gold/20 backdrop-blur-xl p-1.5 z-20"
            style={{ background: 'rgba(15,12,8,0.96)', boxShadow: '0 20px 50px -10px rgba(0,0,0,0.7)' }}>
            {done ? (
              // Tarefa Concluída — não pode reverter, só eliminar
              <div className="px-3 py-2 text-[11px] text-emerald-300/80 flex items-center gap-2">
                <span>🔒</span> Tarefa concluída — bloqueada
              </div>
            ) : (
              <button onClick={() => { setMenuOpen(false); onToggle() }}
                className="w-full text-left text-[12px] px-3 py-2 rounded-lg text-white/70 hover:text-gold hover:bg-gold/10 transition-all flex items-center gap-2">
                <span>✓</span> Marcar como concluída
              </button>
            )}
            <div className="my-1 h-px bg-white/[0.08]" />
            <button onClick={() => {
                setMenuOpen(false)
                if (window.confirm(`Eliminar a tarefa "${t.title}"? Esta ação não pode ser desfeita.`)) onDelete()
              }}
              className="w-full text-left text-[12px] px-3 py-2 rounded-lg text-red-300 hover:text-red-200 hover:bg-red-500/15 transition-all flex items-center gap-2">
              <span>🗑</span> Eliminar Tarefa
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

function Panel({ title, right, children }: { title: string; right?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/[0.06] p-5 backdrop-blur-md"
      style={{ background: 'linear-gradient(135deg, rgba(20,15,8,0.35), rgba(11,11,11,0.65))', boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)' }}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-[14px] font-semibold text-white" style={{ fontFamily: 'Georgia, serif' }}>{title}</h3>
        {right}
      </div>
      {children}
    </div>
  )
}

function Donut({ segments, total }: { segments: { color: string; from: number; to: number }[]; total: number }) {
  const size = 120
  const r = 50
  const c = size / 2
  const strokeW = 14
  const innerR = r - strokeW / 2

  function arc(from: number, to: number) {
    const a1 = (from - 90) * Math.PI / 180
    const a2 = (to - 90) * Math.PI / 180
    const x1 = c + innerR * Math.cos(a1), y1 = c + innerR * Math.sin(a1)
    const x2 = c + innerR * Math.cos(a2), y2 = c + innerR * Math.sin(a2)
    const large = to - from > 180 ? 1 : 0
    return `M ${x1} ${y1} A ${innerR} ${innerR} 0 ${large} 1 ${x2} ${y2}`
  }

  return (
    <div className="relative shrink-0" style={{ width: size, height: size }}>
      <svg width={size} height={size}>
        {/* Background ring */}
        <circle cx={c} cy={c} r={innerR} fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth={strokeW} />
        {segments.map((s, i) => (
          <path key={i} d={arc(s.from, s.to)} fill="none" stroke={s.color} strokeWidth={strokeW} strokeLinecap="round" />
        ))}
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <p className="text-3xl font-bold text-white leading-none">{total}</p>
        <p className="text-[10px] tracking-widest uppercase text-white/40 mt-1">Tarefas</p>
      </div>
    </div>
  )
}

function Legend({ color, label, value }: { color: string; label: string; value: number }) {
  return (
    <div className="flex items-center gap-2 text-[12px]">
      <span className="w-2.5 h-2.5 rounded-full" style={{ background: color, boxShadow: `0 0 6px ${color}99` }} />
      <span className="font-semibold text-white tabular-nums">{value}</span>
      <span className="text-white/55">{label}</span>
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────────
//  MODAL NOVA TAREFA
// ────────────────────────────────────────────────────────────────────────
function ptToIso(d: string): string {
  if (!d) return ''
  const [dd, mm, yyyy] = d.split('/')
  return `${yyyy}-${mm}-${dd}`
}
function isoToPt(iso: string): string {
  if (!iso) return ''
  const [y, m, d] = iso.split('-')
  return `${d}/${m}/${y}`
}

function NovaTarefaModal({
  projects,
  onClose,
  onCreate,
}: {
  projects: Project[]
  onClose: () => void
  onCreate: (task: Task) => void
}) {
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [projectId, setProjectId] = useState<string>('')   // vazio = sem projeto associado
  const [deadlineIso, setDeadlineIso] = useState<string>(ptToIso(TODAY))
  const [hora, setHora] = useState<string>('')
  const [priority, setPriority] = useState<Priority>('Média')
  const [status, setStatus] = useState<TaskStatus>('Pendente')

  // Perfil do freelancer (lido de localStorage — definido em /painel-editor/dados-pessoais)
  const [profile, setProfile] = useState<FreelancerProfile>(DEFAULT_FREELANCER_PROFILE)
  useEffect(() => { setProfile(loadFreelancerProfile()) }, [])

  const [sending, setSending] = useState(false)
  const [feedback, setFeedback] = useState<{ ok: boolean; msg: string } | null>(null)

  // Projeto deixa de ser obrigatório — basta título + prazo
  const valid = title.trim().length > 0 && !!deadlineIso

  function buildTask(): Task {
    const deadline = isoToPt(deadlineIso)
    const id = `user-task-${Date.now()}`
    return {
      id,
      title: title.trim(),
      description: description.trim() || undefined,
      projectId,
      assignee: profile.nome,
      assigneeAvatar: AVATAR_EDITOR,
      deadline,
      hora: hora || undefined,
      priority,
      status,
      progress: status === 'Concluída' ? 100 : status === 'Em andamento' ? 30 : 0,
      autoGenerated: false,
    }
  }

  function submit() {
    if (!valid) return
    onCreate(buildTask())
  }

  async function submitAndNotify() {
    if (!valid) return
    if (!profile.email || !profile.email.includes('@')) {
      setFeedback({ ok: false, msg: 'Email do freelancer inválido. Atualiza em Dados Pessoais.' })
      return
    }
    setSending(true)
    setFeedback(null)
    const task = buildTask()
    const projetoNome = projectId ? projects.find(p => p.id === projectId)?.noivos : undefined
    try {
      const res = await fetch('/api/painel-editor/notify-nova-tarefa', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: profile.email,
          freelancerNome: profile.nome,
          titulo: task.title,
          descricao: task.description,
          projeto: projetoNome,
          prazo: task.deadline,
          hora: task.hora,
          prioridade: task.priority,
          status: task.status,
          // Para onde a resposta do freelancer vai voltar (email do admin RL Photo.Video)
          adminEmail: 'ruimngpro@gmail.com',
        }),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) throw new Error(data.error || 'Falha no envio')
      // Sucesso: cria a tarefa e fecha
      setFeedback({ ok: true, msg: `Email enviado para ${profile.email}` })
      onCreate(task)
    } catch (err: any) {
      setFeedback({ ok: false, msg: `Erro: ${err?.message ?? 'desconhecido'}` })
    } finally {
      setSending(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)' }}>
      <div className="relative w-full max-w-xl rounded-2xl border border-gold/30 overflow-hidden"
        style={{ background: 'linear-gradient(180deg, rgba(20,15,8,0.98), rgba(11,9,5,0.99))', boxShadow: '0 30px 60px -20px rgba(0,0,0,0.8), 0 0 40px -10px rgba(201,164,92,0.35)' }}>
        <button onClick={onClose}
          className="absolute top-3 right-3 w-8 h-8 rounded-lg border border-white/10 text-white/55 hover:text-gold hover:border-gold/30 flex items-center justify-center text-lg z-10">×</button>

        <div className="px-6 pt-6 pb-4 border-b border-white/[0.06]">
          <p className="text-[11px] tracking-[0.4em] uppercase text-gold/70 font-bold mb-2">Criar Tarefa</p>
          <h2 className="text-2xl font-light text-white" style={{ fontFamily: 'Georgia, serif' }}>Nova <span className="italic text-gold">Tarefa</span></h2>
        </div>

        <div className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
          {/* Título */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Título <span className="text-red-400">*</span></p>
            <input value={title} onChange={e => setTitle(e.target.value)}
              placeholder="Ex: Color grading Carolina & Felipe"
              className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white placeholder:text-white/30 focus:outline-none focus:border-gold/50" />
          </div>

          {/* Descrição */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Descrição</p>
            <textarea value={description} onChange={e => setDescription(e.target.value)}
              placeholder="Detalhes adicionais (opcional)"
              rows={3}
              className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white placeholder:text-white/30 focus:outline-none focus:border-gold/50 resize-none" />
          </div>

          {/* Projeto (opcional) */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Projeto <span className="text-white/30 normal-case tracking-normal text-[10px]">(opcional)</span></p>
            <select value={projectId} onChange={e => setProjectId(e.target.value)}
              className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white focus:outline-none focus:border-gold/50">
              <option value="" style={{ background: '#1a1206' }}>— Sem projeto associado —</option>
              {projects.map(p => (
                <option key={p.id} value={p.id} style={{ background: '#1a1206' }}>{p.noivos} — {p.dataCasamento}</option>
              ))}
            </select>
            <p className="text-[10px] text-white/35 mt-1.5 italic">Deixa em branco se a tarefa não estiver ligada a um projeto específico.</p>
          </div>

          {/* Data + Hora */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Prazo <span className="text-red-400">*</span></p>
              <input type="date" value={deadlineIso} onChange={e => setDeadlineIso(e.target.value)}
                className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white focus:outline-none focus:border-gold/50 [color-scheme:dark]" />
            </div>
            <div>
              <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Hora</p>
              <input type="time" value={hora} onChange={e => setHora(e.target.value)}
                className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white focus:outline-none focus:border-gold/50 [color-scheme:dark]" />
            </div>
          </div>

          {/* Prioridade */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Prioridade</p>
            <div className="grid grid-cols-3 gap-2">
              {(['Alta','Média','Baixa'] as Priority[]).map(p => {
                const colorCls =
                  p === 'Alta'  ? (priority === p ? 'bg-red-500/20 border-red-500/50 text-red-300'         : 'border-white/10 text-white/55 hover:border-red-500/30') :
                  p === 'Média' ? (priority === p ? 'bg-yellow-500/20 border-yellow-500/50 text-yellow-300' : 'border-white/10 text-white/55 hover:border-yellow-500/30') :
                                  (priority === p ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-300' : 'border-white/10 text-white/55 hover:border-emerald-500/30')
                return (
                  <button key={p} type="button" onClick={() => setPriority(p)}
                    className={`px-3 py-2.5 rounded-lg border text-[12px] font-semibold tracking-wider transition-all ${colorCls}`}>
                    {p}
                  </button>
                )
              })}
            </div>
          </div>

          {/* Status inicial */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-white/45 font-medium mb-2">Estado inicial</p>
            <select value={status} onChange={e => setStatus(e.target.value as TaskStatus)}
              className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white focus:outline-none focus:border-gold/50">
              {(['Pendente','Em andamento','Em revisão','Bloqueada','Concluída'] as TaskStatus[]).map(s => (
                <option key={s} value={s} style={{ background: '#1a1206' }}>{s}</option>
              ))}
            </select>
          </div>

          {/* Card minimalista — Enviar para o e-mail */}
          <div className="relative rounded-2xl border border-gold/30 overflow-hidden"
            style={{
              background: 'linear-gradient(135deg, rgba(20,15,8,0.6), rgba(11,11,11,0.4))',
              boxShadow: '0 0 30px -8px rgba(201,164,92,0.3), 0 10px 30px -10px rgba(0,0,0,0.5)',
            }}>
            <div className="flex items-center gap-5 p-4 sm:p-5">
              {/* Icon: envelope + paper-plane (gold neon) */}
              <div className="shrink-0 w-16 h-16 sm:w-[72px] sm:h-[72px] rounded-2xl border border-gold/40 flex items-center justify-center relative"
                style={{
                  background: 'radial-gradient(circle at 30% 30%, rgba(201,164,92,0.18), rgba(201,164,92,0.03))',
                  boxShadow: '0 0 18px -4px rgba(201,164,92,0.45), inset 0 0 18px -8px rgba(201,164,92,0.4)',
                }}>
                <svg viewBox="0 0 24 24" className="w-8 h-8 text-gold" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="2.5" y="5" width="15" height="11" rx="1.5" />
                  <path d="M2.5 6.5 L10 12 L17.5 6.5" />
                </svg>
                {/* Paper plane dot */}
                <span className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-black border border-gold/60 flex items-center justify-center"
                  style={{ boxShadow: '0 0 10px rgba(201,164,92,0.5)' }}>
                  <svg viewBox="0 0 24 24" className="w-2.5 h-2.5 text-gold" fill="currentColor">
                    <path d="M21 3L3 10l7 3 3 7 8-17z" />
                  </svg>
                </span>
              </div>

              {/* Divider line */}
              <div className="hidden sm:block w-px h-14 bg-gold/15 shrink-0" />

              {/* Text */}
              <div className="flex-1 min-w-0">
                <p className="text-[10px] sm:text-[11px] tracking-[0.4em] uppercase text-gold/75 font-bold mb-1.5">Nova Tarefa</p>
                <p className="text-[18px] sm:text-[22px] font-light text-white tracking-tight leading-tight" style={{ fontFamily: 'Georgia, serif' }}>
                  Enviar para o e-mail
                </p>
                <p className="text-[11px] sm:text-[12px] text-white/45 mt-1 leading-snug">
                  Envie esta tarefa diretamente para o e-mail e mantenha-se organizado.
                </p>
              </div>

              {/* Action button */}
              <button type="button" onClick={submitAndNotify} disabled={!valid || sending}
                className="shrink-0 inline-flex items-center gap-2 px-4 sm:px-5 py-2.5 sm:py-3 rounded-xl border border-gold/45 text-gold text-[12px] font-semibold tracking-wider hover:bg-gold/10 hover:border-gold/70 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                style={{ boxShadow: '0 0 16px -4px rgba(201,164,92,0.4)' }}>
                {sending ? (
                  <>
                    <span className="inline-block w-3 h-3 border-2 border-gold border-t-transparent rounded-full animate-spin" />
                    A enviar…
                  </>
                ) : (
                  <>
                    <svg viewBox="0 0 24 24" className="w-3.5 h-3.5" fill="currentColor"><path d="M21 3L3 10l7 3 3 7 8-17z" /></svg>
                    Enviar por e-mail
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Feedback do envio */}
          {feedback && (
            <div className={`rounded-lg border px-3 py-2.5 text-[12px] ${
              feedback.ok
                ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'
                : 'border-red-500/30 bg-red-500/10 text-red-300'
            }`}>
              {feedback.ok ? '✓' : '⚠'} {feedback.msg}
            </div>
          )}

          {/* Link discreto: criar sem notificar + cancelar */}
          <div className="flex items-center justify-between gap-3 pt-1">
            <button type="button" onClick={onClose} disabled={sending}
              className="text-[11px] tracking-widest uppercase text-white/40 hover:text-white transition-colors disabled:opacity-40">
              ← Cancelar
            </button>
            <button type="button" onClick={submit} disabled={!valid || sending}
              className="text-[11px] tracking-widest uppercase text-white/40 hover:text-gold transition-colors disabled:opacity-40">
              Criar sem enviar e-mail →
            </button>
          </div>
          <p className="text-[10px] text-white/30 text-center">
            E-mail destino: <span className="text-white/55">{profile.email}</span>
            <Link href="/painel-editor/dados-pessoais" className="ml-2 underline decoration-white/20 hover:text-gold hover:decoration-gold/40 transition-colors">editar</Link>
          </p>
        </div>
      </div>
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────────
//  MODAL CONCLUIR TAREFA — obriga a escrever resultado
// ────────────────────────────────────────────────────────────────────────
function ConcluirTarefaModal({
  task,
  onClose,
  onConfirm,
}: {
  task: Task
  onClose: () => void
  onConfirm: (resultado: string) => void
}) {
  const [resultado, setResultado] = useState('')
  const valid = resultado.trim().length > 0

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)' }}>
      <div className="relative w-full max-w-lg rounded-2xl border border-emerald-500/30 overflow-hidden"
        style={{ background: 'linear-gradient(180deg, rgba(8,18,12,0.98), rgba(5,11,8,0.99))', boxShadow: '0 30px 60px -20px rgba(0,0,0,0.8), 0 0 40px -10px rgba(52,211,153,0.3)' }}>
        <button onClick={onClose}
          className="absolute top-3 right-3 w-8 h-8 rounded-lg border border-white/10 text-white/55 hover:text-emerald-300 hover:border-emerald-500/30 flex items-center justify-center text-lg z-10">×</button>

        <div className="px-6 pt-6 pb-4 border-b border-white/[0.06]">
          <p className="text-[11px] tracking-[0.4em] uppercase text-emerald-400/80 font-bold mb-2">Concluir Tarefa</p>
          <h2 className="text-2xl font-light text-white" style={{ fontFamily: 'Georgia, serif' }}>Marcar como <span className="italic text-emerald-300">concluída</span></h2>
        </div>

        <div className="p-6 space-y-4">
          {/* Tarefa */}
          <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4">
            <p className="text-[10px] tracking-[0.3em] uppercase text-white/40 font-medium mb-1">Tarefa</p>
            <p className="text-[15px] font-medium text-white leading-snug">{task.title}</p>
            <div className="flex items-center gap-2 mt-1.5 flex-wrap">
              <span className={`text-[9px] px-2 py-0.5 rounded-full border tracking-widest uppercase font-bold ${priorityBadge(task.priority)}`}>{task.priority}</span>
              <span className="text-[10px] text-white/35">Prazo · {task.deadline}{task.hora ? ` · ${task.hora}` : ''}</span>
            </div>
          </div>

          {/* Resultado obrigatório */}
          <div>
            <p className="text-[11px] tracking-[0.3em] uppercase text-emerald-400/80 font-bold mb-2">
              Resultado <span className="text-red-400 normal-case tracking-normal text-[10px] ml-1">(obrigatório)</span>
            </p>
            <textarea value={resultado} onChange={e => setResultado(e.target.value)}
              autoFocus
              placeholder="Descreve o que foi feito, decisões tomadas ou notas relevantes…"
              rows={5}
              className="w-full bg-black/40 border border-white/15 rounded-lg px-3 py-2.5 text-[13px] text-white placeholder:text-white/30 focus:outline-none focus:border-emerald-500/50 resize-none leading-relaxed" />
            <p className="text-[10px] text-white/35 mt-1.5">
              {resultado.trim().length > 0
                ? `${resultado.trim().length} caracteres`
                : 'Não é possível concluir sem escrever o resultado.'}
            </p>
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button type="button" onClick={onClose}
              className="flex-1 px-4 py-2.5 rounded-lg border border-white/10 text-white/65 text-[12px] font-semibold tracking-wider hover:border-white/25 hover:text-white transition-all">
              Cancelar
            </button>
            <button type="button" onClick={() => onConfirm(resultado)} disabled={!valid}
              title={!valid ? 'Escreve o resultado antes de concluir.' : undefined}
              className="flex-1 px-4 py-2.5 rounded-lg bg-emerald-500 text-black text-[12px] font-bold tracking-wider hover:bg-emerald-400 transition-all disabled:opacity-40 disabled:cursor-not-allowed disabled:bg-white/[0.04] disabled:text-white/30 flex items-center justify-center gap-2"
              style={valid ? { boxShadow: '0 0 18px -4px rgba(52,211,153,0.5)' } : {}}>
              {valid ? <>✓ Concluir Tarefa</> : <>🔒 Escreve o resultado</>}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
