'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { eventsFromProjects, eventColorFor, PROJECTS, TASKS, TODAY as TODAY_PT, type CalendarEvent, type EventType, type Task, type Priority } from '../_data/projects'
import { NotificationBell } from '../_components/NotificationBell'
import { MessagesBell } from '../_components/MessagesBell'
import { BrandLogo } from '../_components/BrandLogo'
import { getEditorId } from '../_data/freelancer-profile'

// ── Eventos reais da RL para editar (deriva dos trabalhos enviados) ──────────
function EventosRLSection() {
  const [jobs, setJobs] = useState<any[]>([])
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const id = getEditorId()
    if (!id) { setLoaded(true); return }
    let cancelled = false
    fetch(`/api/painel-editor/projetos?freelancer=${id}`)
      .then(r => r.json())
      .then(d => { if (!cancelled) { setJobs(Array.isArray(d?.jobs) ? d.jobs : []); setLoaded(true) } })
      .catch(() => { if (!cancelled) setLoaded(true) })
    return () => { cancelled = true }
  }, [])

  if (!loaded || jobs.length === 0) return null

  const ordered = [...jobs].sort((a, b) => String(a.data_casamento ?? '').localeCompare(String(b.data_casamento ?? '')))
  const fmt = (d: string | null) => d ? new Date(d).toLocaleDateString('pt-PT', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' }) : 'Sem data'

  return (
    <div className="rounded-2xl border border-gold/25 p-5 mb-5"
      style={{ background: 'linear-gradient(180deg, rgba(20,15,8,0.5), rgba(11,11,11,0.7))', boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)' }}>
      <div className="flex items-center gap-2 mb-4">
        <span className="text-gold text-lg">◉</span>
        <h3 className="text-[15px] font-semibold text-white">Eventos da RL para Editar</h3>
        <span className="text-[10px] text-white/35 tracking-widest uppercase">{jobs.length}</span>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {ordered.map((j, i) => (
          <div key={j.notifId ?? i} className="rounded-xl border border-white/10 bg-white/[0.02] p-4">
            <p className="text-[10px] tracking-[0.25em] uppercase text-gold/70 mb-1 capitalize">{fmt(j.data_casamento)}</p>
            <p className="text-[14px] text-white font-medium">{j.noivos || j.local || 'Evento'}</p>
            {j.local && <p className="text-[11px] text-white/45 truncate">{j.local}</p>}
            {Array.isArray(j.downloads) && j.downloads.length > 0 && (
              <a href={j.downloads[0]} target="_blank" rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 mt-2 text-[10px] px-2.5 py-1 rounded-lg bg-gold/15 border border-gold/35 text-gold font-semibold tracking-wider uppercase hover:bg-gold/25 transition-all">↓ Download</a>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Helper: gera eventos a partir dos projetos criados pelo utilizador ──
// (estrutura igual à de eventsFromProjects() em _data/projects.ts)
function addDaysPt(date: string, days: number): string {
  const cleaned = (date || '').split('—')[0].trim() // remove " — HH:MM"
  const [d, m, y] = cleaned.split('/').map(Number)
  if (!d || !m || !y) return ''
  const dt = new Date(y, m-1, d)
  dt.setDate(dt.getDate() + days)
  return `${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}`
}

function stripTime(date: string): string {
  return (date || '').split('—')[0].trim()
}

// Gera tarefas automáticas para um user-project (mesma lógica de /painel-editor/tarefas)
function autoTasksForUserProject(p: any): Task[] {
  const auto: { title: string; priority: Priority; daysAfterCreate: number }[] = [
    { title: 'Importar material',     priority: 'Alta',  daysAfterCreate: 0 },
    { title: 'Organizar ficheiros',   priority: 'Média', daysAfterCreate: 1 },
    { title: 'Iniciar edição',        priority: 'Alta',  daysAfterCreate: 3 },
    { title: 'Color grading',         priority: 'Média', daysAfterCreate: 7 },
    { title: 'Enviar primeira versão', priority: 'Alta', daysAfterCreate: 14 },
  ]
  const recebido = (p.recebido || '').split('—')[0].trim()
  const [d, m, y] = (recebido || '').split('/').map(Number)
  if (!d || !m || !y) return []
  return auto.map((t, i) => {
    const dt = new Date(y, m-1, d); dt.setDate(dt.getDate() + t.daysAfterCreate)
    const deadline = `${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}`
    return {
      id: `${p.id}-task-${i}`,
      title: t.title,
      projectId: p.id,
      assignee: 'Editor Pro',
      deadline,
      priority: t.priority,
      status: 'Pendente' as const,
      progress: 0,
      autoGenerated: true,
    }
  })
}

// ── Trabalhos reais → eventos do calendário ─────────────────────────────
// Só o que existe mesmo na BD: o dia do casamento, o dia em que a RL enviou o
// trabalho, a entrega prevista (quando o admin a definiu) e a entrega feita.
// Nada de datas calculadas por palpite, como nos mocks.
function isoToPtCal(iso: string | null | undefined): string {
  if (!iso) return ''
  const d = new Date(iso)
  if (isNaN(d.getTime())) return ''
  return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`
}

function jobsToEvents(jobs: any[]): CalendarEvent[] {
  const events: CalendarEvent[] = []
  jobs.forEach((j, i) => {
    const o = (j.overrides && typeof j.overrides === 'object') ? j.overrides : {}
    if (o.archived) return
    const id = j.referencia || j.notifId || String(i)
    const nome = o.noivos || j.noivos || j.local || 'Evento'

    const casamento = o.dataCasamento || isoToPtCal(j.data_casamento)
    if (casamento) {
      events.push({ id: `${id}-wed`, title: 'Casamento', subtitle: nome, date: casamento, type: 'Casamento', projectId: id, todoODia: true })
    }

    const recebido = (o.recebido || isoToPtCal(j.sentAt) || '').split('—')[0].trim()
    if (recebido) {
      events.push({ id: `${id}-mat`, title: 'Material Recebido', subtitle: nome, date: recebido, type: 'Prazo', projectId: id, todoODia: true })
    }

    const entregaFeita = isoToPtCal(j.revisao?.entregaEm)
    if (o.entregaPrevista) {
      events.push({ id: `${id}-final`, title: 'Entrega Final', subtitle: nome, date: o.entregaPrevista, type: 'Entrega', projectId: id, todoODia: true, completed: !!entregaFeita })
    }
    if (entregaFeita && entregaFeita !== o.entregaPrevista) {
      events.push({ id: `${id}-entregue`, title: 'Entregue', subtitle: nome, date: entregaFeita, type: 'Entrega', projectId: id, todoODia: true, completed: true })
    }
  })
  return events
}

// Lê TODAS as tarefas (user-criadas + auto-geradas + mocks TASKS) e converte em CalendarEvents.
function userTasksToEvents(): CalendarEvent[] {
  if (typeof window === 'undefined') return []
  const events: CalendarEvent[] = []
  try {
    // 1) Tarefas criadas manualmente em /painel-editor/tarefas
    const userTasksRaw = localStorage.getItem('painel-editor-user-tasks')
    const userTasks: any[] = userTasksRaw ? JSON.parse(userTasksRaw) : []

    // 2) Ids eliminados pelo user
    const deletedRaw = localStorage.getItem('painel-editor-deleted-tasks')
    const deleted = new Set<string>(deletedRaw ? JSON.parse(deletedRaw) : [])

    // 3) Projetos do user (para gerar auto-tasks) + detectar projetos eliminados
    const userProjRaw = localStorage.getItem('painel-editor-user-projects')
    const userProj: any[] = userProjRaw ? JSON.parse(userProjRaw) : []
    const patchesRaw = localStorage.getItem('painel-editor-project-patches')
    const patches: Record<string, any> = patchesRaw ? JSON.parse(patchesRaw) : {}
    const deletedProjIds = new Set<string>()
    Object.entries(patches).forEach(([id, patch]) => {
      if (patch?.archived || patch?.cancelled) deletedProjIds.add(id)
    })

    // 4) Auto-tasks dos user-projects
    const autoUserTasks = userProj.flatMap(autoTasksForUserProject)

    // 5) Merge total: user-criadas + auto-user + mock TASKS (filtra eliminadas + projetos eliminados)
    const allTasks: any[] = [...userTasks, ...autoUserTasks, ...TASKS]
      .filter(t => !deleted.has(t.id))
      .filter(t => !deletedProjIds.has(t.projectId))

    // Deduplica por id (caso haja overlap de auto-geradas com mocks)
    const seen = new Set<string>()
    allTasks.forEach(t => {
      if (!t || !t.deadline || !t.title) return
      if (seen.has(t.id)) return
      seen.add(t.id)
      events.push({
        id: `task-${t.id}`,
        title: t.title,
        subtitle: t.description || (t.projectId ? '' : 'Sem projeto associado'),
        date: t.deadline,
        hora: t.hora,
        type: 'Tarefa',
        projectId: t.projectId,
        todoODia: !t.hora,
        completed: t.status === 'Concluída',
      })
    })
  } catch {}
  return events
}

function userProjectsToEvents(): CalendarEvent[] {
  if (typeof window === 'undefined') return []
  let userProjects: any[] = []
  try {
    const raw = localStorage.getItem('painel-editor-user-projects')
    userProjects = raw ? JSON.parse(raw) : []
  } catch { return [] }

  const events: CalendarEvent[] = []
  userProjects.forEach(p => {
    if (!p.id || !p.noivos) return
    const recebido = stripTime(p.recebido || '')
    const dataCasamento = p.dataCasamento || ''
    const entregaPrevista = p.entregaPrevista || ''

    // 📅 Criação do projeto
    if (recebido) {
      events.push({ id: `${p.id}-create`, title: 'Projeto Recebido', subtitle: p.noivos, date: recebido, type: 'Prazo', projectId: p.id, todoODia: true })
    }

    // 💍 Dia do Casamento
    if (dataCasamento) {
      events.push({ id: `${p.id}-wed`, title: 'Casamento', subtitle: p.noivos, date: dataCasamento, type: 'Casamento', projectId: p.id, todoODia: true })
    }

    // 🟢 Início de Edição (~5 dias depois de criado)
    if (recebido) {
      events.push({ id: `${p.id}-edit`, title: 'Início da Edição', subtitle: p.noivos, date: addDaysPt(recebido, 5), type: 'Prazo', projectId: p.id, todoODia: true })
    }

    // 🟡 Revisão V1 e V2
    if (entregaPrevista) {
      events.push({ id: `${p.id}-v1`, title: 'Revisão V1', subtitle: p.noivos, date: addDaysPt(entregaPrevista, -10), type: 'Revisão', projectId: p.id, todoODia: true })
      events.push({ id: `${p.id}-v2`, title: 'Revisão V2', subtitle: p.noivos, date: addDaysPt(entregaPrevista, -3), type: 'Revisão', projectId: p.id, todoODia: true })
    }

    // 🔵 Entrega Trailer + Entrega Final
    if (entregaPrevista) {
      events.push({ id: `${p.id}-trailer`, title: 'Entrega Trailer', subtitle: p.noivos, date: addDaysPt(entregaPrevista, -5), type: 'Entrega', projectId: p.id, todoODia: true })
      events.push({ id: `${p.id}-final`, title: 'Entrega Final', subtitle: p.noivos, date: entregaPrevista, type: 'Entrega', projectId: p.id, todoODia: true })
    }
  })

  return events
}

// ────────────────────────────────────────────────────────────────────────
//  CALENDÁRIO — Wedding Moments Films
// ────────────────────────────────────────────────────────────────────────

const NAV_ITEMS = [
  { key: 'dashboard',   label: 'Dashboard',           icon: '⌂', href: '/painel-editor' },
  { key: 'novos',       label: 'Novos Projetos',      icon: '+', href: '/painel-editor/novos-projetos' },
  { key: 'pagamentos',  label: 'Pagamentos',          icon: '€', href: '/painel-editor/pagamentos' },
  { key: 'tarefas',     label: 'Tarefas',             icon: '◷', href: '/painel-editor/tarefas' },
  { key: 'calendario',  label: 'Calendário',          icon: '◉', href: '/painel-editor/calendario', active: true },
  { key: 'workflow',    label: 'Workflow',            icon: '☰', href: '/painel-editor/workflow' },
  { key: 'biblioteca',  label: 'Biblioteca',          icon: '♪', href: '/painel-editor/musicas' },
  { key: 'dados',       label: 'Dados Pessoais',      icon: '☻', href: '/painel-editor/dados-pessoais' },
]

const MESES = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
const MESES_SHORT = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
const DIAS = ['DOM','SEG','TER','QUA','QUI','SEX','SÁB']

type ViewMode = 'Mês' | 'Semana' | 'Dia' | 'Agenda'

export default function CalendarioPage() {
  const baseEvents = useMemo(() => eventsFromProjects(), [])
  const [userEvents, setUserEvents] = useState<CalendarEvent[]>([])
  const [taskEvents, setTaskEvents] = useState<CalendarEvent[]>([])
  const [deletedIds, setDeletedIds] = useState<Set<string>>(new Set())
  // Modo real: há editor identificado (?freelancer=<id> ou id já guardado no
  // browser). Aí o calendário mostra só os trabalhos da BD; sem editor, fica o
  // calendário de maquete como estava.
  const [modo, setModo] = useState<'a-resolver' | 'real' | 'maquete'>('a-resolver')
  const [realEvents, setRealEvents] = useState<CalendarEvent[]>([])

  useEffect(() => {
    const id = getEditorId()
    if (!id) { setModo('maquete'); return }
    setModo('real')
    let cancelled = false
    fetch(`/api/painel-editor/projetos?freelancer=${id}`)
      .then(r => r.json())
      .then(d => { if (!cancelled) setRealEvents(jobsToEvents(Array.isArray(d?.jobs) ? d.jobs : [])) })
      .catch(() => {})
    return () => { cancelled = true }
  }, [])

  // Ler projetos + tarefas criados pelo utilizador (localStorage) e gerar os
  // seus eventos — só em modo maquete.
  useEffect(() => {
    if (getEditorId()) return
    function load() {
      setUserEvents(userProjectsToEvents())
      setTaskEvents(userTasksToEvents())
      // Detecta mocks eliminados via patches (archived/cancelled)
      try {
        const raw = localStorage.getItem('painel-editor-project-patches')
        const patches: Record<string, any> = raw ? JSON.parse(raw) : {}
        const deleted = new Set<string>()
        Object.entries(patches).forEach(([id, patch]) => {
          if (patch?.archived || patch?.cancelled) deleted.add(id)
        })
        setDeletedIds(deleted)
      } catch {}
    }
    load()
    const onFocus = () => load()
    window.addEventListener('focus', onFocus)
    return () => window.removeEventListener('focus', onFocus)
  }, [])

  const allEvents = useMemo(() => {
    // Enquanto não se sabe se há editor, não mostra nada — evita um piscar de
    // eventos de maquete a quem tem trabalhos reais.
    if (modo === 'a-resolver') return []
    if (modo === 'real') return realEvents
    // Maquete: filtra eventos de projetos eliminados (archived/cancelled)
    return [...taskEvents, ...userEvents, ...baseEvents].filter(e => !e.projectId || !deletedIds.has(e.projectId))
  }, [modo, realEvents, taskEvents, userEvents, baseEvents, deletedIds])
  // Hoje — derivado do TODAY canónico em _data/projects.ts
  const [TODAY_DAY_NUM, TODAY_MONTH_NUM, TODAY_YEAR_NUM] = TODAY_PT.split('/').map(Number)
  const TODAY_DAY = TODAY_DAY_NUM
  const TODAY_MONTH_IDX = TODAY_MONTH_NUM - 1   // 0-based para Date / setCalView

  const [view, setView] = useState<ViewMode>('Mês')
  const [calView, setCalView] = useState({ y: TODAY_YEAR_NUM, m: TODAY_MONTH_IDX })

  // Salta para mês indicado em ?date=YYYY-MM-DD (vindo do mini-calendar de /tarefas etc.)
  const searchParams = useSearchParams()
  useEffect(() => {
    const dParam = searchParams?.get('date')
    if (!dParam) return
    const [y, m] = dParam.split('-').map(Number)
    if (!y || !m) return
    setCalView({ y, m: m - 1 })
  }, [searchParams])
  const [typeFilter, setTypeFilter] = useState<'Todos' | EventType>('Todos')

  // Eventos do mês (filtrados)
  const eventsThisMonth = useMemo(() => {
    return allEvents.filter(e => {
      const [d, m, y] = e.date.split('/').map(Number)
      const sameMonth = y === calView.y && m - 1 === calView.m
      if (!sameMonth) return false
      if (typeFilter === 'Todos') return true
      return e.type === typeFilter
    })
  }, [allEvents, calView, typeFilter])

  // Grouping por dia
  const eventsByDay = useMemo(() => {
    const map = new Map<number, CalendarEvent[]>()
    eventsThisMonth.forEach(e => {
      const day = parseInt(e.date.split('/')[0], 10)
      if (!map.has(day)) map.set(day, [])
      map.get(day)!.push(e)
    })
    return map
  }, [eventsThisMonth])

  // Grid (5-6 weeks)
  const firstDay = new Date(calView.y, calView.m, 1).getDay()
  const lastDate = new Date(calView.y, calView.m + 1, 0).getDate()
  const prevLastDate = new Date(calView.y, calView.m, 0).getDate()

  type Cell = { day: number; current: boolean; month: number; year: number }
  const cells: Cell[] = []
  for (let i = firstDay - 1; i >= 0; i--) cells.push({ day: prevLastDate - i, current: false, month: calView.m - 1, year: calView.y })
  for (let d = 1; d <= lastDate; d++) cells.push({ day: d, current: true, month: calView.m, year: calView.y })
  while (cells.length % 7 !== 0) cells.push({ day: cells.length - lastDate - firstDay + 1, current: false, month: calView.m + 1, year: calView.y })

  // Próximos Eventos (todos os meses, ordenados, próximos 5)
  const proximos = useMemo(() => {
    const todayKey = `${calView.y}-${String(calView.m+1).padStart(2,'0')}-15` // mock today = 15 do mês actual
    return [...allEvents]
      .map(e => {
        const [d,m,y] = e.date.split('/').map(Number)
        return { e, key: `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}` }
      })
      .filter(x => x.key >= todayKey)
      .sort((a, b) => a.key.localeCompare(b.key))
      .slice(0, 5)
      .map(x => x.e)
  }, [allEvents, calView])

  // Resumo do mês (donut)
  const summary = useMemo(() => {
    const types: EventType[] = ['Casamento','Prazo','Entrega','Revisão','Pagamento','Reunião']
    const items = types.map(t => ({
      type: t,
      label: t === 'Casamento' ? 'Casamentos' :
             t === 'Prazo'     ? 'Prazos' :
             t === 'Entrega'   ? 'Entregas' :
             t === 'Revisão'   ? 'Revisões' :
             t === 'Pagamento' ? 'Pagamentos' :
                                'Reunião',
      value: eventsThisMonth.filter(e => e.type === t).length,
      color: eventColorFor(t).dot,
    }))
    const total = items.reduce((s, it) => s + it.value, 0)
    return { items, total }
  }, [eventsThisMonth])

  function changeMonth(delta: number) {
    const d = new Date(calView.y, calView.m + delta, 1)
    setCalView({ y: d.getFullYear(), m: d.getMonth() })
  }

  return (
    <div className="min-h-screen text-white relative" style={{ background: '#0A0A0A' }}>
      <div className="pointer-events-none fixed inset-0 z-0" style={{ background: 'radial-gradient(ellipse 80% 60% at 80% 15%, rgba(201,164,92,0.07), transparent 65%)' }} />
      <div className="pointer-events-none fixed inset-0 z-0" style={{ background: 'radial-gradient(ellipse 60% 50% at 15% 85%, rgba(201,164,92,0.05), transparent 70%)' }} />

      <Sidebar />

      <main className="relative z-10 pl-[250px]">
        <div className="px-6 sm:px-8 py-6 max-w-[1700px] mx-auto">

          {/* HERO */}
          <Hero />

          {/* Eventos reais da RL para editar */}
          <EventosRLSection />

          {/* GRID */}
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-5 mt-5">

            {/* MAIN — Calendar */}
            <div className="flex flex-col gap-4">

              {/* View modes + Filters */}
              <div className="flex items-center justify-between gap-3 -mt-2 mb-1">
                <div className="flex items-center gap-1 p-1 rounded-xl border border-white/[0.06] bg-black/30">
                  {(['Mês','Semana','Dia','Agenda'] as ViewMode[]).map(v => (
                    <button key={v} onClick={() => setView(v)}
                      className={`px-4 py-1.5 rounded-lg text-[12px] tracking-wide transition-all ${
                        view === v ? 'bg-gold/15 text-gold border border-gold/35' : 'text-white/45 hover:text-white/85'
                      }`}>{v}</button>
                  ))}
                </div>
              </div>

              {/* Calendar Card */}
              <div className="rounded-2xl border border-white/[0.06] p-5 backdrop-blur-md"
                style={{ background: 'linear-gradient(135deg, rgba(20,15,8,0.4), rgba(11,11,11,0.6))', boxShadow: '0 20px 50px -20px rgba(0,0,0,0.6)' }}>

                {/* Toolbar */}
                <div className="flex items-center justify-between gap-3 flex-wrap mb-4">
                  <div className="flex items-center gap-2">
                    <button onClick={() => changeMonth(-1)} className="w-9 h-9 rounded-lg border border-white/10 text-white/55 hover:text-gold hover:border-gold/30 transition-all">‹</button>
                    <button onClick={() => changeMonth(1)}  className="w-9 h-9 rounded-lg border border-white/10 text-white/55 hover:text-gold hover:border-gold/30 transition-all">›</button>
                    <button onClick={() => setCalView({ y: TODAY_YEAR_NUM, m: TODAY_MONTH_IDX })} className="px-4 h-9 rounded-lg border border-white/10 text-white/70 hover:text-gold hover:border-gold/30 transition-all text-[12px] tracking-widest uppercase">Hoje</button>
                    <p className="text-[18px] font-light text-white ml-3" style={{ fontFamily: 'Georgia, serif' }}>
                      {MESES[calView.m]} {calView.y} <span className="text-white/30 text-base">▾</span>
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <select value={typeFilter} onChange={e => setTypeFilter(e.target.value as any)}
                      className="bg-black/30 border border-white/[0.08] rounded-lg px-3 py-1.5 text-[12px] text-white/70 focus:outline-none focus:border-gold/40 cursor-pointer">
                      <option>Todos os tipos</option>
                      <option>Casamento</option>
                      <option>Tarefa</option>
                      <option>Prazo</option>
                      <option>Entrega</option>
                      <option>Revisão</option>
                      <option>Pagamento</option>
                      <option>Reunião</option>
                    </select>
                  </div>
                </div>

                {/* ── VIEW: MÊS ─────────────────────────────────────── */}
                {view === 'Mês' && (
                  <>
                    {/* Dias semana */}
                    <div className="grid grid-cols-7 gap-1 mb-1">
                      {DIAS.map((d, i) => (
                        <div key={i} className="text-center text-[10px] tracking-[0.3em] uppercase text-white/35 py-2">{d}</div>
                      ))}
                    </div>

                    {/* Grid */}
                    <div className="grid grid-cols-7 gap-1.5">
                      {cells.map((c, i) => {
                        const isToday = c.current && c.day === TODAY_DAY && c.month === TODAY_MONTH_IDX && c.year === TODAY_YEAR_NUM
                        const dayEvents = c.current ? (eventsByDay.get(c.day) ?? []) : []
                        return (
                          <div key={i}
                            className={`relative min-h-[110px] rounded-xl p-2 border transition-all ${
                              c.current
                                ? 'border-white/[0.05] hover:border-gold/20 hover:bg-white/[0.02]'
                                : 'border-transparent opacity-30'
                            }`}>
                            <div className="flex items-center justify-between mb-1.5">
                              {isToday ? (
                                <span className="w-7 h-7 rounded-full bg-gold text-black text-[13px] font-bold flex items-center justify-center"
                                  style={{ boxShadow: '0 0 14px rgba(201,164,92,0.55)' }}>{c.day}</span>
                              ) : (
                                <span className={`text-[13px] ${c.current ? 'text-white/85 font-medium' : 'text-white/30'}`}>{c.day}</span>
                              )}
                              {dayEvents.length > 2 && (
                                <span className="text-[9px] text-white/35">+{dayEvents.length - 2}</span>
                              )}
                            </div>

                            <div className="space-y-1">
                              {dayEvents.slice(0, 2).map(ev => {
                                const color = eventColorFor(ev.type)
                                return (
                                  <div key={ev.id} className="flex items-start gap-1.5">
                                    <span className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0" style={{ background: color.dot }} />
                                    <div className="min-w-0 flex-1">
                                      <p className={`text-[10.5px] font-medium leading-tight truncate ${ev.completed ? 'line-through text-white/35' : 'text-white/85'}`}>
                                        {ev.hora ? <span className="text-white/55 mr-1">{ev.hora}</span> : null}
                                        {ev.title}
                                      </p>
                                      {ev.subtitle && (
                                        <p className="text-[10px] text-white/40 truncate">{ev.subtitle}</p>
                                      )}
                                    </div>
                                  </div>
                                )
                              })}
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </>
                )}

                {/* ── VIEW: SEMANA ──────────────────────────────────── */}
                {view === 'Semana' && (
                  <SemanaView events={allEvents} todayY={TODAY_YEAR_NUM} todayM={TODAY_MONTH_IDX} todayD={TODAY_DAY} />
                )}

                {/* ── VIEW: DIA ─────────────────────────────────────── */}
                {view === 'Dia' && (
                  <DiaView events={allEvents} todayY={TODAY_YEAR_NUM} todayM={TODAY_MONTH_IDX} todayD={TODAY_DAY} />
                )}

                {/* ── VIEW: AGENDA ──────────────────────────────────── */}
                {view === 'Agenda' && (
                  <AgendaView events={allEvents} />
                )}

                {/* Legend */}
                <div className="flex flex-wrap items-center justify-center gap-x-4 gap-y-2 mt-5 pt-5 border-t border-white/[0.04]">
                  {[
                    { type: 'Casamento' as EventType, label: 'Casamentos' },
                    { type: 'Tarefa' as EventType,    label: 'Tarefas' },
                    { type: 'Prazo' as EventType,     label: 'Prazos' },
                    { type: 'Entrega' as EventType,   label: 'Entregas' },
                    { type: 'Revisão' as EventType,   label: 'Revisões' },
                    { type: 'Pagamento' as EventType, label: 'Pagamentos' },
                    { type: 'Reunião' as EventType,   label: 'Reuniões' },
                  ].map(l => {
                    const c = eventColorFor(l.type)
                    return (
                      <span key={l.type} className="inline-flex items-center gap-1.5 text-[11px] text-white/55">
                        <span className="w-2 h-2 rounded-full" style={{ background: c.dot, boxShadow: `0 0 6px ${c.dot}99` }} />
                        {l.label}
                      </span>
                    )
                  })}
                </div>
                {/* legenda já apresentada acima */}
              </div>
            </div>

            {/* RIGHT PANEL */}
            <aside className="flex flex-col gap-4">

              {/* Próximos Eventos */}
              <Panel title="Próximos Eventos" right={<button className="text-[11px] tracking-wider uppercase text-gold/70 hover:text-gold transition-colors">Ver todos</button>}>
                <div className="space-y-3">
                  {proximos.map(ev => {
                    const color = eventColorFor(ev.type)
                    const [d, m] = ev.date.split('/').map(Number)
                    return (
                      <div key={ev.id} className="flex items-start gap-3">
                        <div className="text-center shrink-0">
                          <p className="text-[18px] font-bold text-white leading-none">{String(d).padStart(2,'0')}</p>
                          <p className="text-[10px] text-gold tracking-widest uppercase">{MESES_SHORT[m-1].toUpperCase()}</p>
                        </div>
                        <div className="flex-1 min-w-0 pl-3 border-l border-white/[0.06]">
                          <p className="text-[12px] font-medium text-white truncate flex items-center gap-1.5">
                            <span className="w-1.5 h-1.5 rounded-full" style={{ background: color.dot }} />
                            {ev.title}
                          </p>
                          {ev.subtitle && <p className="text-[11px] text-white/50 truncate">{ev.subtitle}</p>}
                          <p className="text-[10px] text-white/30 mt-0.5">{ev.hora ?? 'Todo o dia'}</p>
                        </div>
                        <span className={`text-[10px] px-2 py-0.5 rounded-md border tracking-widest uppercase font-bold ${color.badge}`}>{ev.type}</span>
                      </div>
                    )
                  })}
                </div>
              </Panel>

              {/* Sincronização */}
              <div className="rounded-2xl border border-emerald-500/15 p-4 backdrop-blur-md"
                style={{ background: 'linear-gradient(135deg, rgba(16,40,28,0.4), rgba(11,11,11,0.5))' }}>
                <div className="flex items-center justify-between mb-2">
                  <p className="text-[14px] font-semibold text-white" style={{ fontFamily: 'Georgia, serif' }}>Sincronização</p>
                  <button className="w-8 h-8 rounded-lg border border-emerald-500/25 bg-emerald-500/10 text-emerald-300 hover:bg-emerald-500/20 transition-all flex items-center justify-center">↻</button>
                </div>
                <p className="text-[12px] text-emerald-300 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" style={{ boxShadow: '0 0 6px rgba(52,211,153,0.7)' }} />
                  Sincronizado com o dashboard
                </p>
                <p className="text-[10px] text-white/40 mt-1">Última atualização: agora</p>
              </div>

              {/* Resumo do Mês */}
              <Panel title="Resumo do Mês">
                <div className="flex items-center gap-5">
                  <Donut items={summary.items.map(it => ({ value: it.value, color: it.color }))} total={summary.total} label="Eventos" />
                  <div className="flex-1 space-y-2">
                    {summary.items.map(it => (
                      <div key={it.type} className="flex items-center gap-2 text-[12px]">
                        <span className="w-2 h-2 rounded-full" style={{ background: it.color, boxShadow: `0 0 6px ${it.color}99` }} />
                        <span className="font-semibold text-white tabular-nums w-4">{it.value}</span>
                        <span className="text-white/55">{it.label}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </Panel>

              {/* Google Calendar */}
              <button className="w-full inline-flex items-center justify-center gap-2 px-4 py-3 rounded-2xl border border-white/[0.08] bg-white/[0.02] hover:border-gold/30 hover:bg-gold/[0.04] transition-all text-[12px] text-white/75">
                <span>📅</span>
                <span className="font-medium tracking-wider">Conectar ao Google Calendar</span>
              </button>

            </aside>
          </div>

          <p className="text-center text-[10px] tracking-[0.4em] uppercase text-white/15 mt-12 mb-4">RL Photo.Video · Calendário sincronizado</p>
        </div>
      </main>
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────────
//  COMPONENTS
// ────────────────────────────────────────────────────────────────────────

function Sidebar() {
  return (
    <aside
      className="flex fixed top-0 left-0 bottom-0 w-[250px] z-30 flex-col"
      style={{
        background: 'linear-gradient(180deg, rgba(15,12,8,0.96) 0%, rgba(11,9,5,0.98) 100%)',
        backdropFilter: 'blur(20px)',
        borderRight: '1px solid rgba(201,164,92,0.12)',
      }}>
      <BrandLogo />
      <nav className="flex-1 overflow-y-auto px-3 py-5 space-y-0.5">
        {NAV_ITEMS.map(it => {
          const isActive = !!it.active
          const cls = `w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-left transition-all group ${
            isActive ? 'bg-gold/10 border border-gold/30 text-gold' : 'border border-transparent text-white/45 hover:text-white/90 hover:bg-white/[0.03]'
          }`
          const inner = (
            <>
              <span className={`w-5 text-center text-base ${isActive ? 'text-gold' : 'text-white/35 group-hover:text-white/70'}`}>{it.icon}</span>
              <span className="text-[13px] font-medium tracking-wide">{it.label}</span>
            </>
          )
          return it.href
            ? <Link key={it.key} href={it.href} className={cls} style={isActive ? { boxShadow: '0 0 18px -4px rgba(201,164,92,0.35)' } : {}}>{inner}</Link>
            : <button key={it.key} className={cls}>{inner}</button>
        })}
      </nav>

      {/* Sync card */}
      <div className="px-4 pb-3">
        <div className="rounded-xl border border-gold/15 p-3"
          style={{ background: 'linear-gradient(135deg, rgba(201,164,92,0.06), transparent)' }}>
          <div className="flex items-start gap-2">
            <span className="text-gold text-base">📅</span>
            <p className="text-[11px] text-white/55 leading-relaxed">Tudo sincronizado com o dashboard</p>
          </div>
          <p className="text-[10px] text-emerald-400 mt-2 flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" style={{ boxShadow: '0 0 6px rgba(52,211,153,0.7)' }} />
            Atualizado agora em tempo real
          </p>
        </div>
      </div>

      <div className="px-4 py-3 border-t border-white/[0.04]">
        <div className="flex items-center gap-3 p-2 rounded-xl bg-white/[0.02] border border-white/[0.06]">
          <div className="relative w-10 h-10 rounded-full overflow-hidden border border-gold/40 shrink-0">
            <img src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=80&h=80&fit=crop&crop=face" alt="" className="w-full h-full object-cover" />
            <span className="absolute bottom-0 right-0 w-2.5 h-2.5 rounded-full bg-emerald-400 border border-black" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-[12px] font-semibold text-white truncate">Editor Pro</p>
            <p className="text-[10px] text-white/35 truncate">editorpro@mail.com</p>
            <p className="text-[9px] text-emerald-400 mt-0.5">● Online</p>
          </div>
        </div>
      </div>
    </aside>
  )
}

function Hero() {
  return (
    <div className="relative overflow-hidden rounded-3xl border border-white/[0.08]"
      style={{ boxShadow: '0 30px 60px -20px rgba(0,0,0,0.6)' }}>
      <div className="absolute inset-0 z-0">
        <img src="https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1600&h=300&fit=crop"
          alt="" className="w-full h-full object-cover" style={{ filter: 'blur(1.5px)' }} />
      </div>
      <div className="absolute inset-0 z-[1]"
        style={{ background: 'linear-gradient(90deg, rgba(10,10,10,0.96) 0%, rgba(10,10,10,0.85) 35%, rgba(10,10,10,0.45) 70%, rgba(10,10,10,0.05) 100%)' }} />
      <div className="relative z-10 flex items-center justify-between gap-6 px-8 sm:px-12 py-7">
        <div className="flex items-center gap-5 max-w-xl">
          <div className="w-16 h-16 rounded-2xl border border-gold/40 flex items-center justify-center text-3xl text-gold shrink-0"
            style={{ background: 'radial-gradient(circle at 30% 30%, rgba(201,164,92,0.18), rgba(201,164,92,0.04))', boxShadow: '0 0 22px -4px rgba(201,164,92,0.3)' }}>📅</div>
          <div>
            <h1 className="text-4xl sm:text-5xl font-light text-white tracking-tight" style={{ fontFamily: 'Georgia, serif' }}>Calendário</h1>
            <p className="text-[13px] text-white/55 mt-1 leading-relaxed">Visualize todos os eventos, prazos e entregas sincronizados com os projetos.</p>
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <NotificationBell />
          <MessagesBell />
          <button className="w-11 h-11 rounded-2xl border border-white/15 bg-black/40 backdrop-blur-md hover:border-gold/40 transition-all flex items-center justify-center">
            <span className="text-lg text-white/75">📅</span>
          </button>
          <button className="inline-flex items-center gap-2 px-5 h-11 rounded-xl bg-gold text-black text-[13px] font-semibold tracking-wider hover:bg-gold/90 transition-all"
            style={{ boxShadow: '0 0 24px -4px rgba(201,164,92,0.5)' }}>
            <span className="text-lg leading-none">+</span> Novo Evento
          </button>
        </div>
      </div>
    </div>
  )
}

function Panel({ title, right, children }: { title: string; right?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/[0.06] p-5 backdrop-blur-md"
      style={{ background: 'linear-gradient(135deg, rgba(20,15,8,0.35), rgba(11,11,11,0.65))', boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)' }}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-[14px] font-semibold text-white" style={{ fontFamily: 'Georgia, serif' }}>{title}</h3>
        {right}
      </div>
      {children}
    </div>
  )
}

function Donut({ items, total, label }: { items: { value: number; color: string }[]; total: number; label: string }) {
  const size = 130
  const r = 55
  const c = size / 2
  const strokeW = 14
  const innerR = r - strokeW / 2

  const segs: { color: string; from: number; to: number }[] = []
  let acc = 0
  items.forEach(it => {
    if (it.value === 0 || total === 0) return
    const from = acc
    const to = acc + (it.value / total) * 360
    segs.push({ color: it.color, from, to })
    acc = to
  })

  function arc(from: number, to: number) {
    const a1 = (from - 90) * Math.PI / 180
    const a2 = (to - 90) * Math.PI / 180
    const x1 = c + innerR * Math.cos(a1), y1 = c + innerR * Math.sin(a1)
    const x2 = c + innerR * Math.cos(a2), y2 = c + innerR * Math.sin(a2)
    const large = to - from > 180 ? 1 : 0
    return `M ${x1} ${y1} A ${innerR} ${innerR} 0 ${large} 1 ${x2} ${y2}`
  }

  return (
    <div className="relative shrink-0" style={{ width: size, height: size }}>
      <svg width={size} height={size}>
        <circle cx={c} cy={c} r={innerR} fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth={strokeW} />
        {segs.map((s, i) => (
          <path key={i} d={arc(s.from, s.to)} fill="none" stroke={s.color} strokeWidth={strokeW} strokeLinecap="round" />
        ))}
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <p className="text-3xl font-bold text-white leading-none">{total}</p>
        <p className="text-[10px] tracking-widest uppercase text-white/40 mt-1">{label}</p>
      </div>
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────────
//  VIEWS: SEMANA · DIA · AGENDA
// ────────────────────────────────────────────────────────────────────────

/** Constrói uma data 'DD/MM/YYYY' a partir de (y, m, d) */
function buildPt(y: number, m: number, d: number): string {
  return `${String(d).padStart(2,'0')}/${String(m+1).padStart(2,'0')}/${y}`
}

function eventsForDate(events: CalendarEvent[], pt: string): CalendarEvent[] {
  return events.filter(e => e.date === pt).sort((a, b) => (a.hora ?? '').localeCompare(b.hora ?? ''))
}

// ── SEMANA ──────────────────────────────────────────────────────────────
function SemanaView({ events, todayY, todayM, todayD }: { events: CalendarEvent[]; todayY: number; todayM: number; todayD: number }) {
  const [weekStart, setWeekStart] = useState(() => {
    const t = new Date(todayY, todayM, todayD)
    const dow = t.getDay() // 0 = Domingo
    t.setDate(t.getDate() - dow)
    return t
  })

  const days: Date[] = []
  for (let i = 0; i < 7; i++) {
    const d = new Date(weekStart); d.setDate(weekStart.getDate() + i); days.push(d)
  }
  const DIAS_FULL = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado']

  function shift(delta: number) {
    const d = new Date(weekStart); d.setDate(d.getDate() + delta * 7); setWeekStart(d)
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4 px-1">
        <button onClick={() => shift(-1)} className="text-[11px] tracking-widest uppercase text-white/55 hover:text-gold transition-colors px-3 py-1 rounded-md border border-white/10">‹ Semana</button>
        <p className="text-[14px] text-white font-light" style={{ fontFamily: 'Georgia, serif' }}>
          {buildPt(days[0].getFullYear(), days[0].getMonth(), days[0].getDate())} — {buildPt(days[6].getFullYear(), days[6].getMonth(), days[6].getDate())}
        </p>
        <button onClick={() => shift(1)} className="text-[11px] tracking-widest uppercase text-white/55 hover:text-gold transition-colors px-3 py-1 rounded-md border border-white/10">Semana ›</button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-7 gap-2">
        {days.map((d, i) => {
          const pt = buildPt(d.getFullYear(), d.getMonth(), d.getDate())
          const dayEvents = eventsForDate(events, pt)
          const isToday = d.getFullYear() === todayY && d.getMonth() === todayM && d.getDate() === todayD
          return (
            <div key={i} className={`rounded-xl border p-3 min-h-[180px] ${isToday ? 'border-gold/45 bg-gold/[0.04]' : 'border-white/[0.06] bg-white/[0.02]'}`}
              style={isToday ? { boxShadow: '0 0 18px -4px rgba(201,164,92,0.35)' } : {}}>
              <div className="flex items-center justify-between mb-2">
                <div>
                  <p className="text-[9px] tracking-widest uppercase text-white/35">{DIAS_FULL[d.getDay()].slice(0,3)}</p>
                  <p className={`text-[22px] font-bold leading-none ${isToday ? 'text-gold' : 'text-white/85'}`}>{d.getDate()}</p>
                </div>
                {dayEvents.length > 0 && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-gold/15 border border-gold/30 text-gold font-bold">{dayEvents.length}</span>
                )}
              </div>
              <div className="space-y-1.5">
                {dayEvents.slice(0, 5).map(ev => {
                  const color = eventColorFor(ev.type)
                  return (
                    <div key={ev.id} className="flex items-start gap-1.5 group cursor-pointer">
                      <span className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0" style={{ background: color.dot }} />
                      <div className="min-w-0 flex-1">
                        <p className={`text-[11px] font-medium leading-tight truncate ${ev.completed ? 'line-through text-white/35' : 'text-white/85'} group-hover:text-gold transition-colors`}>
                          {ev.title}
                        </p>
                        {ev.subtitle && <p className="text-[10px] text-white/40 truncate">{ev.subtitle}</p>}
                      </div>
                    </div>
                  )
                })}
                {dayEvents.length > 5 && (
                  <p className="text-[10px] text-white/35 pt-0.5">+{dayEvents.length - 5} mais</p>
                )}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── DIA ─────────────────────────────────────────────────────────────────
function DiaView({ events, todayY, todayM, todayD }: { events: CalendarEvent[]; todayY: number; todayM: number; todayD: number }) {
  const [day, setDay] = useState(() => new Date(todayY, todayM, todayD))

  function shift(delta: number) {
    const d = new Date(day); d.setDate(d.getDate() + delta); setDay(d)
  }

  const pt = buildPt(day.getFullYear(), day.getMonth(), day.getDate())
  const dayEvents = eventsForDate(events, pt)
  const DIAS_FULL = ['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado']

  // Slots de hora (06:00 → 22:00)
  const slots = Array.from({ length: 17 }, (_, i) => `${String(6 + i).padStart(2,'0')}:00`)
  const eventsByHora = new Map<string, CalendarEvent[]>()
  dayEvents.forEach(ev => {
    const h = ev.hora?.split(':')[0] ? `${ev.hora.split(':')[0].padStart(2,'0')}:00` : 'Todo o dia'
    if (!eventsByHora.has(h)) eventsByHora.set(h, [])
    eventsByHora.get(h)!.push(ev)
  })
  const todoODia = eventsByHora.get('Todo o dia') ?? []

  return (
    <div>
      <div className="flex items-center justify-between mb-4 px-1">
        <button onClick={() => shift(-1)} className="text-[11px] tracking-widest uppercase text-white/55 hover:text-gold transition-colors px-3 py-1 rounded-md border border-white/10">‹ Dia anterior</button>
        <div className="text-center">
          <p className="text-[10px] tracking-widest uppercase text-gold/60">{DIAS_FULL[day.getDay()]}</p>
          <p className="text-[20px] text-white font-light" style={{ fontFamily: 'Georgia, serif' }}>{pt}</p>
        </div>
        <button onClick={() => shift(1)} className="text-[11px] tracking-widest uppercase text-white/55 hover:text-gold transition-colors px-3 py-1 rounded-md border border-white/10">Dia seguinte ›</button>
      </div>

      {/* Todo o dia */}
      {todoODia.length > 0 && (
        <div className="mb-4">
          <p className="text-[10px] tracking-widest uppercase text-white/40 mb-2">Todo o dia</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {todoODia.map(ev => {
              const color = eventColorFor(ev.type)
              return (
                <div key={ev.id} className="flex items-center gap-3 p-3 rounded-xl border border-white/[0.06] bg-white/[0.02] hover:border-gold/25 transition-all cursor-pointer">
                  <span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: color.dot, boxShadow: `0 0 6px ${color.dot}99` }} />
                  <div className="flex-1 min-w-0">
                    <p className={`text-[13px] font-medium ${ev.completed ? 'line-through text-white/35' : 'text-white/85'}`}>{ev.title}</p>
                    {ev.subtitle && <p className="text-[11px] text-white/50">{ev.subtitle}</p>}
                  </div>
                  <span className={`text-[10px] px-2 py-0.5 rounded-md border tracking-widest uppercase font-bold ${color.badge}`}>{ev.type}</span>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Timeline horária */}
      <div className="space-y-1">
        {slots.map(slot => {
          const evs = eventsByHora.get(slot) ?? []
          return (
            <div key={slot} className="grid grid-cols-[60px_1fr] gap-3 items-start py-2 border-t border-white/[0.04]">
              <p className="text-[11px] text-white/40 font-mono tabular-nums">{slot}</p>
              <div className="space-y-1.5 min-h-[1.25rem]">
                {evs.length === 0 ? (
                  <p className="text-[11px] text-white/15 italic">—</p>
                ) : (
                  evs.map(ev => {
                    const color = eventColorFor(ev.type)
                    return (
                      <div key={ev.id} className="flex items-center gap-2 px-2.5 py-1.5 rounded-lg border border-white/[0.06] hover:border-gold/25 transition-all cursor-pointer"
                        style={{ background: `${color.dot}10` }}>
                        <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ background: color.dot }} />
                        <p className="text-[12px] font-medium text-white/85 truncate flex-1">{ev.title}</p>
                        {ev.subtitle && <span className="text-[10px] text-white/50 hidden sm:inline">· {ev.subtitle}</span>}
                      </div>
                    )
                  })
                )}
              </div>
            </div>
          )
        })}
      </div>

      {dayEvents.length === 0 && (
        <div className="mt-6 text-center py-10 rounded-xl border border-dashed border-white/[0.08]">
          <p className="text-[14px] text-white/35">Sem eventos neste dia.</p>
        </div>
      )}
    </div>
  )
}

// ── AGENDA ──────────────────────────────────────────────────────────────
function AgendaView({ events }: { events: CalendarEvent[] }) {
  const sorted = useMemo(() => [...events].sort((a, b) => {
    const ka = a.date.split('/').reverse().join('-') + (a.hora ?? '')
    const kb = b.date.split('/').reverse().join('-') + (b.hora ?? '')
    return ka.localeCompare(kb)
  }), [events])

  // Agrupar por mês
  const groups: Record<string, CalendarEvent[]> = {}
  sorted.forEach(ev => {
    const [, m, y] = ev.date.split('/').map(Number)
    const key = `${y}-${String(m).padStart(2,'0')}`
    if (!groups[key]) groups[key] = []
    groups[key].push(ev)
  })

  return (
    <div className="space-y-6">
      {Object.entries(groups).map(([key, group]) => {
        const [y, m] = key.split('-').map(Number)
        return (
          <div key={key}>
            <div className="flex items-center gap-3 mb-3">
              <h3 className="text-[14px] font-semibold text-white" style={{ fontFamily: 'Georgia, serif' }}>
                {MESES[m - 1]} {y}
              </h3>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-gold/10 border border-gold/25 text-gold font-bold">{group.length}</span>
              <div className="flex-1 h-px bg-white/[0.06]" />
            </div>
            <div className="space-y-2">
              {group.map(ev => {
                const color = eventColorFor(ev.type)
                const [d, mn] = ev.date.split('/').map(Number)
                return (
                  <div key={ev.id} className="flex items-center gap-4 p-3 rounded-xl border border-white/[0.06] bg-white/[0.02] hover:border-gold/25 transition-all cursor-pointer">
                    <div className="text-center shrink-0 w-12">
                      <p className="text-[22px] font-bold text-white leading-none">{String(d).padStart(2,'0')}</p>
                      <p className="text-[9px] text-gold tracking-widest uppercase">{MESES_SHORT[mn - 1]}</p>
                    </div>
                    <span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: color.dot, boxShadow: `0 0 6px ${color.dot}99` }} />
                    <div className="flex-1 min-w-0">
                      <p className={`text-[14px] font-medium ${ev.completed ? 'line-through text-white/35' : 'text-white/90'}`}>{ev.title}</p>
                      {ev.subtitle && <p className="text-[11px] text-white/45">{ev.subtitle}</p>}
                    </div>
                    <p className="text-[11px] text-white/40 font-mono shrink-0">{ev.hora ?? 'Todo o dia'}</p>
                    <span className={`text-[10px] px-2 py-0.5 rounded-md border tracking-widest uppercase font-bold shrink-0 ${color.badge}`}>{ev.type}</span>
                  </div>
                )
              })}
            </div>
          </div>
        )
      })}
      {sorted.length === 0 && (
        <div className="text-center py-16 rounded-xl border border-dashed border-white/[0.08]">
          <p className="text-[14px] text-white/35">Sem eventos.</p>
        </div>
      )}
    </div>
  )
}
